<a href="https://colab.research.google.com/github/nrios256-create/analisis_datos/blob/main/prescripciones_limpias_%5BRios_Sepulveda%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [957]:
import pandas as pd #aqui le digo que cada vez que escriba pd significa pandas, pandas un excel pero dentro de python
import numpy as np #numpy es la  base matematica, hacer calculos y demas
import seaborn as sns #es como matplot o sea hacer graficos pero  mas bonitos y organizados
import matplotlib.pyplot as plt #hacer graficos

##***********************************************************************************************************************************
#**CARGAR DATOS Y VERIFICARLOS**

In [958]:
#cargar drive
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [959]:
#importar modulo os y ver el contenido de la carpeta
import os
os.getcwd()

'/content/drive/My Drive/ciencia de datos/analisis de datos/segundo corte'

In [960]:
os.chdir('/content/drive/MyDrive/ciencia de datos/analisis de datos/segundo corte')
#cambiar a directorio o carpeta que elegi

In [961]:
os.listdir()
#mirar la lista que hay en la carpeta que elegi

['Salud mental.ipynb',
 'limpieza de datos parte 01.ipynb',
 'datos_crudos.ipynb',
 'merging dataframe.ipynb',
 'Union 27 04.ipynb',
 'prescripciones_raw_rios_sepulveda.csv',
 'prescripciones limpias_[Rios Sepulveda].ipynb']

In [962]:
prescripciones= pd.read_csv('prescripciones_raw_rios_sepulveda.csv')
#leer  el archivo

##***********************************************************************************************************************************

#**Nivel 1: Diagnostico**

1. Cargue el dataset con pandas. Reporte forma, tipos de dato, nombres de columnas y las
primeras cinco filas.

In [963]:
prescripciones.head(20)
# reviso las primeras filas del dataset para ver como vienen los datos

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
0,4355,2024-03-08,ENALAPRIL,250.0,VO,K29.5,79.586599,72.0,Compensar,MED-2771
1,4442,03/09/2023,ASA,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,NuevaEPS,MED-9403
2,8015,2026-04-10,Enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN
3,4887,19/01/2026,METFORMINA,500.0,subcutanea,hipertension,85.277837,NaN,COMPENSAR,MED-4463
4,1406,junio 18 2024,metformina,250.0,IV,NaN,71.785582,47.0,Nueva EPS,MED-5819
5,7309,2026-03-24,Amoxicilina,850.0,Oral,Z00.0,63.396508,67.0,Sura,NaN
6,4337,2026-01-26,Ibuprofeno,200.0,via oral,E11,85.457759,23.0,COMPENSAR,MED-8594
7,9589,2025-06-29,Ibuprofeno,250.0,IV,NaN,83.736521,34.0,EPS Sanitas,MED-7444
8,2976,2024-08-26,Enalapril,250.0,Oral,K29.5,39.603594,63.0,SANITAS,MED-8023
9,2647,2024-10-16,Ibuprofeno,250.0,IV,diabetes tipo 2,78.122144,64.0,SANITAS,NaN


In [964]:
prescripciones.info()
# miro la informacion general del dataset como tipos de datos y valores no nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   id_paciente         520 non-null    int64  
 1   fecha_prescripcion  520 non-null    object 
 2   medicamento         520 non-null    object 
 3   dosis_mg            488 non-null    object 
 4   via_administracion  520 non-null    object 
 5   diagnostico_cie10   419 non-null    object 
 6   peso_paciente_kg    500 non-null    float64
 7   edad                504 non-null    float64
 8   eps                 520 non-null    object 
 9   prescriptor_id      471 non-null    object 
dtypes: float64(2), int64(1), object(7)
memory usage: 40.8+ KB


In [965]:
prescripciones.columns
#reviso los nombre de las columnas que coincidan con mi dataset de excel que se me fue entregado

Index(['id_paciente', 'fecha_prescripcion', 'medicamento', 'dosis_mg',
       'via_administracion', 'diagnostico_cie10', 'peso_paciente_kg', 'edad',
       'eps', 'prescriptor_id'],
      dtype='object')

In [966]:
# reviso la forma del dataset (filas, columnas)
prescripciones.shape

(520, 10)

In [967]:
# reviso los tipos de datos de cada columna
prescripciones.dtypes

,0
id_paciente,int64
fecha_prescripcion,object
medicamento,object
dosis_mg,object
via_administracion,object
diagnostico_cie10,object
peso_paciente_kg,float64
edad,float64
eps,object
prescriptor_id,object


In [968]:
prescripciones.describe()
#reviso los datos como la desviacion, maximos y minimos y datos que a lo mejor esten fuera del estandar

,id_paciente,peso_paciente_kg,edad
count,520.000000,500.000000,504.000000
mean,5616.323077,69.686264,50.934524
std,2538.428992,36.587824,21.881792
min,1170.000000,2.000000,-1.000000
25%,3503.750000,59.690991,34.000000
50%,5676.000000,67.420535,51.000000
75%,7779.500000,75.949301,67.000000
max,9984.000000,600.000000,200.000000


#**Markdown**

Profe, en esta primera parte hice una inspección inicial del dataset para entender cómo vienen los datos antes de hacer cualquier limpieza.

primero utilicé head() para ver las primeras filas y así tener una idea general de cómo está estructurada la información. Desde ahí se pueden notar varias inconsistencias, por ejemplo en la columna de fechas hay diferentes formatos (algunos en formato YYYY-MM-DD, otros con / y otros en texto), también en medicamento hay diferencias en mayúsculas y minúsculas, y en via_administracion se ven distintas formas para lo mismo.

luego usé info() para revisar los tipos de datos y los valores no nulos. Aquí se evidencia que varias columnas tienen datos faltantes como dosis_mg, diagnostico_cie10, peso_paciente_kg, edad y prescriptor_id, lo cual coincide con lo que se menciona en el contexto del dataset.

después revisé las columnas con columns para verificar que los nombres coinciden con los planteados en el archivo original, y en este caso todo está correcto, no hay columnas adicionales ni errores en los nombres.

también usé shape para confirmar la dimensión del dataset, el cual tiene 520 filas y 10 columnas.

con dtypes observé que la mayoría de columnas están como tipo object, lo cual indica que más adelante se va a necesitar hacer conversiones, por ejemplo en fechas o en variables que deberían ser numéricas como dosis_mg.

finalmente utilicé describe() para ver un resumen estadístico de las variables numéricas como edad y peso_paciente_kg. Esto me permitió identificar posibles valores atípicos o errores, por ejemplo se observa una edad mínima de -1 y una máxima de 200, lo cual no es lógico en un contexto real, y también un peso máximo de 600 kg que claramente es un valor fuera de rango.

básicamente, este análisis inicial confirma que el dataset presenta varios problemas de calidad como valores faltantes, formatos inconsistentes y datos atípicos, por lo que será necesario aplicar un proceso de limpieza cuidadoso en las siguientes etapas.



#*******************************************************************************************************************

2. Calcule el número y porcentaje de valores faltantes por columna. Presente los resultados
en una Serie o DataFrame ordenado de mayor a menor completitud.

In [969]:
# calculo la cantidad de valores nulos por cada columna
valores_faltantes = prescripciones.isnull().sum()
# uso isnull() para identificar los valores nulos (NaN) dentro del dataset
# luego uso sum() para contar cuantos valores nulos hay en cada columna

In [970]:
# calculo el porcentaje de valores nulos
porcentaje_faltantes = (valores_faltantes / len(prescripciones)) * 100
# uso len(prescripciones) para obtener el total de registros (filas) del dataset
# luego divido la cantidad de nulos entre el total de filas para obtener la proporción
# multiplico por 100 para convertirlo en porcentaje

# uno ambos resultados en un solo dataframe para verlo mejor
tabla_faltantes = pd.DataFrame({
    'faltantes': valores_faltantes,
    # aquí creo una columna llamada 'faltantes' donde guardo la cantidad de valores nulos

    'porcentaje (%)': porcentaje_faltantes
    # aquí creo otra columna donde guardo el porcentaje de valores nulos
})
# uso pd.DataFrame para organizar la información en forma de tabla y poder visualizarla mejor

In [971]:
# ordeno de mayor a menor según la cantidad de faltantes
tabla_faltantes = tabla_faltantes.sort_values(by='faltantes', ascending=False)
# uso sort_values para ordenar la tabla según la columna 'faltantes'
# ascending=False significa que lo ordeno de mayor a menor

# muestro la tabla
tabla_faltantes
# esto me permite ver el resultado final organizado

,faltantes,porcentaje (%)
diagnostico_cie10,101,19.423077
prescriptor_id,49,9.423077
dosis_mg,32,6.153846
peso_paciente_kg,20,3.846154
edad,16,3.076923
id_paciente,0,0.000000
fecha_prescripcion,0,0.000000
medicamento,0,0.000000
via_administracion,0,0.000000
eps,0,0.000000


#**Markdown**

Profe, en esta parte revisé los valores faltantes por cada columna del dataset. primero conté cuántos datos nulos hay usando isnull() y sum(), y luego calculé el porcentaje teniendo en cuenta el total de registros.

al organizar la información se puede ver claramente cuáles columnas tienen más problemas. por ejemplo, diagnostico_cie10 es la que más valores faltantes tiene con 101 registros, seguido por prescriptor_id con 49 y dosis_mg con 32. también se ven faltantes en peso_paciente_kg y edad, aunque en menor cantidad.

en cambio, columnas como id_paciente, fecha_prescripcion, medicamento, via_administracion y eps no presentan valores nulos, lo cual indica que están completas en ese sentido.

esto es importante porque no todas las columnas tienen el mismo nivel de problema, entonces más adelante no se pueden tratar igual. por ejemplo, en columnas como edad o peso_paciente_kg no sería correcto eliminar datos sin analizar, ya que son variables importantes dentro de un contexto clínico.

este análisis me ayuda a tener claro en qué columnas debo enfocarme más cuando haga la limpieza.

#*******************************************************************************************************************

3. En una celda Markdown, documente cada problema encontrado por columna. Incluya el
tipo de problema (tipo incorrecto, valor invalido, inconsistencia categórica, duplicados, etc.)
y un ejemplo concreto.

In [972]:
# reviso los valores únicos de la columna medicamento
prescripciones['medicamento'].unique()
# uso unique() para ver todos los valores diferentes que existen en la columna
# esto me ayuda a identificar inconsistencias como mayúsculas, minúsculas o nombres diferentes

array(['ENALAPRIL', 'ASA', 'Enalapril', 'METFORMINA', 'metformina',
       'Amoxicilina', 'Ibuprofeno ', 'amoxicilina', 'ibuprofeno',
       'Aspirina ', 'Metformina 500'], dtype=object)

In [973]:
# reviso los valores únicos de la vía de administración
prescripciones['via_administracion'].unique()
# nuevamente uso unique() para ver cómo están escritos los valores
# esto me permite detectar si hay diferentes formas de escribir lo mismo

array(['VO', 'subcutanea', 'intravenosa', 'IV', 'Oral', 'via oral', 'SC',
       'oral', 'Intravenosa', 'Subcutanea'], dtype=object)

In [974]:
# reviso los valores únicos de la eps
prescripciones['eps'].unique()
# esto me ayuda a ver si hay variaciones en los nombres de las eps (por ejemplo con o sin espacios o en mayúsculas)

array(['Compensar', 'NuevaEPS', 'Sanitas', 'COMPENSAR', 'Nueva EPS',
       'Sura', 'EPS Sanitas', 'SANITAS', 'SURA', 'nueva eps', 'EPS Sura'],
      dtype=object)

In [975]:
# reviso estadísticas de la edad
prescripciones['edad'].describe()
# uso describe() para ver valores como mínimo, máximo, promedio y cuartiles
# esto me ayuda a identificar valores atípicos como edades negativas o muy altas

,edad
count,504.000000
mean,50.934524
std,21.881792
min,-1.000000
25%,34.000000
50%,51.000000
75%,67.000000
max,200.000000


In [976]:
# reviso estadísticas del peso
prescripciones['peso_paciente_kg'].describe()
# nuevamente uso describe() para analizar la distribución del peso
# esto me permite detectar valores fuera de rango como pesos demasiado altos

,peso_paciente_kg
count,500.000000
mean,69.686264
std,36.587824
min,2.000000
25%,59.690991
50%,67.420535
75%,75.949301
max,600.000000


In [977]:
# busco registros donde la edad sea menor a 0
prescripciones[prescripciones['edad'] < 0]
# uso esta condición para filtrar solo los casos donde la edad es negativa
# esto me permite ver ejemplos concretos de datos inválidos

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
102,7975,16/02/2026,Aspirina,500.0,VO,NaN,NaN,-1.0,nueva eps,MED-6162
451,1489,2023-06-15,Enalapril,NaN,SC,I10,62.120201,-1.0,Sura,MED-2960
454,5087,marzo 9 2024,Aspirina,100mg,Subcutanea,hipertension,54.723294,-1.0,Nueva EPS,MED-1589


In [978]:
# busco registros donde el peso sea mayor a 200 kg
prescripciones[prescripciones['peso_paciente_kg'] > 200]
# uso este filtro para identificar posibles fuera de rango en el peso
# 200 kg se toma como referencia para detectar valores poco realistas

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
33,8964,2024-10-30,ibuprofeno,850.0,Subcutanea,NaN,450.0,36.0,NuevaEPS,MED-3052
319,4273,09/04/2024,Ibuprofeno,850mg,Oral,K29.5,600.0,36.0,EPS Sanitas,MED-0953
335,6282,18/05/2024,Metformina 500,400.0,subcutanea,Z00.0,450.0,83.0,NuevaEPS,MED-7678


In [979]:
# reviso los valores unicos de la dosis
prescripciones['dosis_mg'].unique()
# esto me ayuda a ver si hay mezcla de numeros y texto (por ejemplo '100mg')

array(['250.0', '400.0', '200.0', '500.0', '850.0', nan, '100.0',
       '1000.0', '-500.0', '-200.0', '-850.0', '-100.0', '50000.0',
       '400mg', '200mg', '850mg', '100mg', '-250mg', '500mg', '-400.0',
       '1000mg', '-1000.0'], dtype=object)

In [980]:
# reviso algunos valores de la fecha
prescripciones['fecha_prescripcion'].head(10)
# esto me permite ver los diferentes formatos en los que viene la fecha

,fecha_prescripcion
0,2024-03-08
1,03/09/2023
2,2026-04-10
3,19/01/2026
4,junio 18 2024
5,2026-03-24
6,2026-01-26
7,2025-06-29
8,2024-08-26
9,2024-10-16


In [981]:
# reviso si hay registros duplicados
prescripciones.duplicated().sum()
# esto me permite saber si hay filas exactamente iguales

# reviso duplicados parciales por paciente
prescripciones['id_paciente'].duplicated().sum()
# esto me ayuda a ver si un paciente aparece varias veces

np.int64(33)

In [982]:
# reviso ejemplos de duplicados completos
prescripciones[prescripciones.duplicated()]
# esto me permite ver ejemplos concretos de filas repetidas

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
500,7828,28/12/2025,amoxicilina,250.0,Intravenosa,I10,67.896301,21.0,Nueva EPS,MED-9741
501,3006,2024-10-14,METFORMINA,850.0,subcutanea,NaN,88.007742,23.0,SURA,MED-4054
502,3627,2024-01-05,ibuprofeno,400.0,oral,Z00.0,65.324436,56.0,EPS Sura,MED-5551
503,8617,2023-12-05,Ibuprofeno,NaN,oral,E11,50.170370,45.0,SANITAS,NaN
504,6350,2024-04-16,ibuprofeno,500.0,via oral,E11,58.017781,58.0,NuevaEPS,MED-9832
505,2959,2024-09-03,Ibuprofeno,100.0,oral,NaN,60.016445,78.0,Sura,NaN
506,4220,2024-11-01,Enalapril,500.0,via oral,I10,89.075624,41.0,SURA,MED-3263
507,4629,03/12/2023,Amoxicilina,500.0,SC,Z00.0,64.267690,53.0,SANITAS,MED-0215
508,1653,2026-02-22,ibuprofeno,500.0,VO,K29.5,84.450763,NaN,SANITAS,MED-1189
509,4040,2026-01-22,Amoxicilina,250.0,via oral,I10,66.093916,69.0,COMPENSAR,MED-5989


#**Markdown**

profe, en esta parte hice una revisión más detallada por cada columna para identificar los problemas que tiene el dataset antes de hacer cualquier limpieza.

empezando por id_paciente, se puede ver que hay registros repetidos, ya que al revisar duplicados aparecen varios casos donde el mismo paciente se repite. esto no necesariamente es un error, pero sí es importante tenerlo en cuenta porque puede afectar análisis si no se controla bien.

en la columna fecha_prescripcion encontré un problema de formato, ya que hay diferentes formas de representar la fecha, por ejemplo aparecen valores como "2024-03-08", "03/09/2023" y también texto como "junio 18 2024". esto es una inconsistencia de formato que se debe estandarizar más adelante.

en medicamento se observan inconsistencias categóricas, ya que el mismo medicamento aparece escrito de diferentes formas, por ejemplo "ENALAPRIL", "Enalapril" y también "metformina" y "METFORMINA". esto indica que no hay una normalización en los nombres.

en dosis_mg hay varios problemas, primero hay valores nulos, pero además hay mezcla de tipos de datos, ya que aparecen números como "250.0" pero también strings como "100mg" o "500mg". adicionalmente hay valores negativos como "-200.0" y valores extremadamente altos como "50000.0", lo cual representa datos inválidos y posibles outliers.

en la columna via_administracion también se ven inconsistencias categóricas, ya que hay diferentes formas de representar lo mismo, por ejemplo "VO", "oral", "via oral", "IV", "intravenosa", "Subcutanea", "SC", entre otras. esto muestra que no hay estandarización en esta variable.

en diagnostico_cie10 se presenta una mezcla de formatos, ya que hay códigos como "K29.5" o "E11", pero también texto como "hipertension" o "diabetes tipo 2", además de valores faltantes. esto indica una inconsistencia en el tipo de dato y presencia de NaN.

en peso_paciente_kg se identifican valores faltantes y también valores fuera de rango, por ejemplo aparece un peso máximo de 600 kg, lo cual no es realista y se considera un outlier.

en la columna edad también hay problemas, ya que existen valores faltantes, edades negativas como -1 y valores muy altos como 200, lo cual corresponde a datos inválidos.

en eps se presentan inconsistencias categóricas, ya que una misma entidad aparece con diferentes nombres como "Compensar", "COMPENSAR", "Nueva EPS", "NuevaEPS", "nueva eps", entre otros. esto indica falta de normalización.

por último, en prescriptor_id se observan valores faltantes y además un formato tipo texto como "MED-2771", lo cual puede ser válido pero debe revisarse si es consistente en todos los registros.

con todo esto se puede ver que el dataset tiene varios tipos de problemas como valores faltantes, inconsistencias categóricas, errores de formato, valores inválidos y outliers, por lo que es necesario hacer una limpieza cuidadosa en los siguientes pasos.

#*******************************************************************************************************************

#**Nivel 2: Limpieza**

4. Estandarice fecha_prescripcion a tipo datetime. Use pd.to_datetime con errors='coerce'.
Justifique que hace con los NaT resultantes.

In [983]:
# convierto la columna fecha_prescripcion a tipo datetime
prescripciones['fecha_prescripcion'] = pd.to_datetime(
    prescripciones['fecha_prescripcion'],
    errors='coerce'
)

# uso pd.to_datetime para transformar los valores de la columna a formato fecha
# errors='coerce' sirve para que los valores que no se puedan convertir se conviertan en NaT (valor nulo de fechas)

# reviso cuantos valores quedaron como NaT despues de la conversion
prescripciones['fecha_prescripcion'].isnull().sum()
# uso isnull() para identificar los valores que quedaron como nulos
# sum() me permite contar cuantos NaT se generaron

np.int64(201)

In [984]:
# reviso como quedo la columna despues de la conversion
prescripciones['fecha_prescripcion'].head()
# esto me permite ver si la conversion se hizo correctamente

,fecha_prescripcion
0,2024-03-08
1,NaT
2,2026-04-10
3,NaT
4,NaT


In [985]:
prescripciones['fecha_prescripcion'].dtype
#confirmar que sí quedó como datetime

dtype('<M8[ns]')

In [986]:
prescripciones= pd.read_csv('prescripciones_raw_rios_sepulveda.csv')
#vuelvo y lo traigo porque necesito reiniciar el dataset varias veces por errores que cometi haciendo el codigo y me queda mas cerca

In [987]:
# guardo una copia de la columna fecha_prescripcion antes de convertirla
prescripciones['fecha_original'] = prescripciones['fecha_prescripcion']
# aquí creo una nueva columna llamada fecha_original
# uso prescripciones['fecha_prescripcion'] porque es la columna que tiene las fechas en texto
# hago esto porque cuando convierta la fecha, los valores que fallen se vuelven NaT y se pierde el texto original
# esto me sirve para poder revisar después cuál fue el error real en las fechas que no se pudieron convertir

# convierto la columna fecha_prescripcion a tipo datetime
prescripciones['fecha_prescripcion'] = pd.to_datetime(
    prescripciones['fecha_prescripcion'],
    errors='coerce'
)
# uso pd.to_datetime porque necesito transformar la columna de texto a formato fecha
# uso prescripciones['fecha_prescripcion'] porque es la columna que el profe pide estandarizar
# uso errors='coerce' para que los valores que no se puedan convertir no generen error
# en lugar de fallar, pandas convierte esos valores en NaT (nulo en formato fecha)
# esto me permite identificar fácilmente cuáles fechas tienen problemas de formato

# reviso cuántas fechas quedaron como NaT después de la conversión
cantidad_nat_fechas = prescripciones['fecha_prescripcion'].isnull().sum()
# uso isnull() para identificar las fechas que quedaron como NaT
# uso sum() para contar cuántos valores nulos hay en la columna
# guardo el resultado en cantidad_nat_fechas para poder usarlo después

# muestro la cantidad de fechas que no se pudieron convertir
cantidad_nat_fechas
# esto me permite ver cuántos registros tienen problema en la fecha

np.int64(201)

In [988]:
# calculo el porcentaje de fechas que quedaron como NaT
porcentaje_nat_fechas = prescripciones['fecha_prescripcion'].isnull().mean() * 100
# uso isnull() para marcar como True las fechas que quedaron como NaT
# uso mean() porque los True valen 1 y los False valen 0, entonces me da la proporción de fechas con error
# multiplico por 100 para convertir esa proporción en porcentaje
# esto me ayuda a entender qué tan grande es el problema dentro del dataset

# muestro el porcentaje de fechas con problema
porcentaje_nat_fechas
# esto me sirve para justificar después la decisión que tome con esos NaT

np.float64(38.65384615384615)

In [989]:
# reviso las fechas originales que no se pudieron convertir
fechas_con_error = prescripciones.loc[
    prescripciones['fecha_prescripcion'].isnull(),
    ['fecha_original', 'fecha_prescripcion']
]
# uso loc porque necesito filtrar filas específicas del dataframe
# uso la condición isnull() para quedarme solo con las fechas que fallaron
# selecciono fecha_original para ver cómo venía escrita la fecha antes de convertirse
# selecciono fecha_prescripcion para confirmar que quedó como NaT
# guardo esto en fechas_con_error para analizar los errores

# muestro algunos ejemplos de las fechas con error
fechas_con_error.head(20)
# uso head(20) para ver una muestra de los errores sin mostrar toda la tabla
# esto me permite identificar si el problema es formato, texto o escritura incorrecta o rara

,fecha_original,fecha_prescripcion
1,03/09/2023,NaT
3,19/01/2026,NaT
4,junio 18 2024,NaT
10,22/01/2025,NaT
11,24/02/2026,NaT
15,abril 18 2026,NaT
18,mayo 13 2024,NaT
20,26/05/2023,NaT
21,noviembre 30 2024,NaT
24,septiembre 25 2024,NaT


In [990]:
# intento convertir SOLO las fechas que quedaron como NaT usando dayfirst=True
prescripciones.loc[
    prescripciones['fecha_prescripcion'].isnull(),
    'fecha_prescripcion'
] = pd.to_datetime(
    prescripciones.loc[
        prescripciones['fecha_prescripcion'].isnull(),
        'fecha_original'
    ],
    errors='coerce',
    dayfirst=True
)
# uso loc para modificar solo ciertas filas del dataframe
# uso la condición isnull() para seleccionar únicamente las fechas que fallaron en el primer intento
# esto me evita dañar las fechas que ya estaban bien convertidas
# uso fecha_original porque ahí está el valor original en texto
# uso pd.to_datetime para intentar convertir nuevamente esas fechas
# uso errors='coerce' para que las que no se puedan convertir sigan como NaT
# uso dayfirst=True porque esas fechas vienen en formato día/mes/año

prescripciones['fecha_prescripcion'].isnull().sum()
# uso isnull() para identificar las fechas que quedaron como NaT
# uso sum() para contar cuántos valores nulos hay en la columna

np.int64(77)

In [991]:
# reviso primero cuáles fechas siguen quedando como NaT
fechas_pendientes = prescripciones[prescripciones['fecha_prescripcion'].isnull()]['fecha_original']
# uso isnull() para identificar las fechas que todavía no se pudieron convertir
# filtro esas filas para ver solamente las fechas que siguen con problema
# selecciono fecha_original porque ahí está el texto real como venía en el archivo

# muestro algunas fechas pendientes
fechas_pendientes.head(20)
# uso head(20) para mirar una muestra y confirmar qué tipo de formato sigue fallando

,fecha_original
4,junio 18 2024
15,abril 18 2026
18,mayo 13 2024
21,noviembre 30 2024
24,septiembre 25 2024
47,septiembre 17 2023
60,junio 27 2024
66,noviembre 25 2024
67,diciembre 13 2025
88,febrero 25 2024


In [992]:
# creo un diccionario para cambiar los meses en español por su número
meses = {
    'enero': '01',
    'febrero': '02',
    'marzo': '03',
    'abril': '04',
    'mayo': '05',
    'junio': '06',
    'julio': '07',
    'agosto': '08',
    'septiembre': '09',
    'octubre': '10',
    'noviembre': '11',
    'diciembre': '12'
}
# uso un diccionario porque necesito relacionar cada mes escrito con su número
# por ejemplo, junio debe pasar a 06 y noviembre debe pasar a 11
# hago esto porque pandas no está reconociendo bien los meses escritos en español

# tomo solo las fechas que todavía siguen como NaT
fechas_pendientes = prescripciones[prescripciones['fecha_prescripcion'].isnull()]['fecha_original']
# uso isnull() para identificar las fechas que siguen sin convertirse
# filtro el dataframe para quedarme solo con esas filas
# selecciono fecha_original porque ahí está la fecha como venía escrita desde el archivo

# paso esas fechas pendientes a minúsculas
fechas_texto_pendientes = fechas_pendientes.str.lower()
# uso str.lower() para asegurarme de que todos los meses estén en minúscula
# esto evita problemas si algún mes viene escrito con mayúscula o mezclado

# reemplazo los meses escritos por números
fechas_texto_pendientes = fechas_texto_pendientes.replace(meses, regex=True)
# uso replace para cambiar cada mes por el número que puse en el diccionario
# uso regex=True porque el mes está dentro de una fecha completa, por ejemplo "junio 18 2024"
# esto deja la fecha en una forma más fácil de convertir, por ejemplo "06 18 2024"

# reviso cómo quedaron algunas fechas después del reemplazo
fechas_texto_pendientes.head(20)
# uso head(20) para mirar una muestra y comprobar que los meses sí cambiaron por números

,fecha_original
4,06 18 2024
15,04 18 2026
18,05 13 2024
21,11 30 2024
24,09 25 2024
47,09 17 2023
60,06 27 2024
66,11 25 2024
67,12 13 2025
88,02 25 2024


In [993]:
# convierto las fechas pendientes usando el formato mes día año
fecha_3 = pd.to_datetime(fechas_texto_pendientes, format='%m %d %Y', errors='coerce')
# uso pd.to_datetime para convertir esas fechas a tipo datetime
# uso format='%m %d %Y' porque después del reemplazo quedan como mes día año
# por ejemplo, "06 18 2024" significa mes 06, día 18 y año 2024
# uso errors='coerce' para que si alguna fecha no se puede convertir quede como NaT y no dañe el código

# completo la columna fecha_prescripcion con las fechas que logré convertir en este tercer intento
prescripciones['fecha_prescripcion'] = prescripciones['fecha_prescripcion'].fillna(fecha_3)
# uso fillna() porque solo quiero rellenar los espacios que todavía estaban como NaT
# esto me permite conservar las fechas que ya estaban bien convertidas antes
# así no borro ni daño información que ya estaba correcta

# reviso cuántas fechas siguen como NaT después de este intento
prescripciones['fecha_prescripcion'].isnull().sum()
# uso isnull() para identificar las fechas que todavía siguen como NaT
# uso sum() para contar cuántas fechas no se pudieron recuperar
# esto me permite saber si ya terminé de limpiar esta columna

np.int64(0)

In [994]:
prescripciones.head()
#reviso como se va viendo la tabla

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id,fecha_original
0,4355,2024-03-08,ENALAPRIL,250.0,VO,K29.5,79.586599,72.0,Compensar,MED-2771,2024-03-08
1,4442,2023-09-03,ASA,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,NuevaEPS,MED-9403,03/09/2023
2,8015,2026-04-10,Enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN,2026-04-10
3,4887,2026-01-19,METFORMINA,500.0,subcutanea,hipertension,85.277837,NaN,COMPENSAR,MED-4463,19/01/2026
4,1406,2024-06-18,metformina,250.0,IV,NaN,71.785582,47.0,Nueva EPS,MED-5819,junio 18 2024


In [995]:
# elimino la columna fecha_original porque ya solo era una columna de apoyo
prescripciones = prescripciones.drop(columns=['fecha_original'])
# uso drop(columns=...) porque quiero eliminar una columna completa, no filas con datos nulos
# elimino fecha_original porque ya logré usarla para comparar y rescatar las fechas que habían quedado como NaT
# no uso dropna() porque no estoy eliminando registros por valores faltantes
# esto no afecta la información limpia, solo quita una columna auxiliar que ya no necesito

# reviso las primeras filas para confirmar que fecha_original ya no aparece
prescripciones.head()
# uso head() para mirar rápidamente si la tabla quedó con la columna fecha_prescripcion limpia y sin la columna auxiliar

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
0,4355,2024-03-08,ENALAPRIL,250.0,VO,K29.5,79.586599,72.0,Compensar,MED-2771
1,4442,2023-09-03,ASA,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,NuevaEPS,MED-9403
2,8015,2026-04-10,Enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN
3,4887,2026-01-19,METFORMINA,500.0,subcutanea,hipertension,85.277837,NaN,COMPENSAR,MED-4463
4,1406,2024-06-18,metformina,250.0,IV,NaN,71.785582,47.0,Nueva EPS,MED-5819


In [996]:
# guardo el dataset después de dejar limpia la columna fecha_prescripcion
prescripciones_avance = prescripciones.copy()
# uso copy() para guardar una copia del dataframe con el punto 4 ya terminado
# esto me sirve para no perder la limpieza de fechas cuando pase al siguiente punto

#**Markdown**

profe, en esta parte trabajé la columna fecha_prescripcion porque venía con varios formatos diferentes. primero intenté convertirla con pd.to_datetime y errors='coerce', como se pedía en el punto, y ahí me quedaron 201 valores como NaT. esos NaT no los eliminé, porque primero quería entender qué estaba pasando con ellos.

algo que me costó entender fue que cuando una fecha queda como NaT, ya se pierde la forma original en que venía escrita. por eso tuve que crear una columna auxiliar llamada fecha_original, para poder comparar la fecha original con la fecha convertida. esa parte me confundió bastante al inicio, porque yo pensaba que fecha_prescripcion debía mostrarme todavía el dato original, pero después entendí que al convertirla pandas ya reemplaza los valores que fallan por NaT.

revisando los errores encontré que había fechas en formato día/mes/año, por ejemplo 19/01/2026, y también fechas con meses escritos en español como junio 18 2024, abril 18 2026 y noviembre 30 2024. primero intenté recuperar las fechas usando dayfirst=True, y con eso los NaT bajaron de 201 a 77. eso me mostró que una parte grande del problema era por la interpretación del día y el mes.

después revisé las fechas que todavía seguían como NaT y vi que eran las que tenían los meses escritos en español. ahí me tocó buscar una forma más parecida a lo que hemos trabajado en clase, porque muchos ejemplos usan loc y for, pero yo quería hacerlo con herramientas más cercanas a lo que ya hemos usado en los colabs, como diccionarios, replace, fillna y pd.to_datetime. entonces creé un diccionario para cambiar los meses en español por números y luego convertí esas fechas usando un formato específico de mes, día y año.

con ese proceso logré que la columna fecha_prescripcion quedara completamente convertida a tipo datetime y sin valores NaT. no eliminé registros, sino que intenté rescatar la información antes de tomar cualquier decisión. la columna fecha_original solo fue una columna de apoyo para revisar los errores, entonces al final la eliminé con drop(columns=...), no con dropna(), porque no estaba borrando datos faltantes sino quitando una columna auxiliar que ya había cumplido su función.

algo importante es que inicialmente los NaT no los eliminé ni usé dropna(), porque en un dataset de salud eso implicaría perder información que puede ser relevante. en lugar de eso, primero analicé la causa de los errores y fui haciendo varios intentos de conversión para rescatar la mayor cantidad posible de datos. al final logré convertir todas las fechas correctamente, por lo que no fue necesario eliminar registros.

#*******************************************************************************************************************

5. Limpie dosis_mg: (a) extraiga el valor numérico de strings mixtos como '100mg', (b) decida
como tratar valores negativos y justifique su criterio, (c) impute los NaN con la mediana por
medicamento usando groupby y transform.

In [997]:
# recupero el dataset desde el avance anterior
prescripciones = prescripciones_avance.copy()
# uso copy() para seguir trabajando desde el dataset que ya tiene limpia la fecha_prescripcion
# esto evita que al iniciar el punto 5 se pierda lo que ya hice en el punto 4

In [998]:
# reviso los valores únicos de la columna dosis_mg
prescripciones['dosis_mg'].unique()
# uso ['dosis_mg'] para seleccionar la columna que quiero analizar
# uso unique() para ver todos los valores diferentes que existen
# esto me ayuda a identificar problemas como:
# - números como texto ('100.0')
# - strings con unidades ('100mg')
# - valores negativos
# - valores nulos

array(['250.0', '400.0', '200.0', '500.0', '850.0', nan, '100.0',
       '1000.0', '-500.0', '-200.0', '-850.0', '-100.0', '50000.0',
       '400mg', '200mg', '850mg', '100mg', '-250mg', '500mg', '-400.0',
       '1000mg', '-1000.0'], dtype=object)

In [999]:
# limpio la columna dosis_mg quitando el texto 'mg'
prescripciones['dosis_mg'] = prescripciones['dosis_mg'].astype(str).str.replace('mg', '')
# uso astype(str) para convertir todo a texto
# esto me permite trabajar con funciones de string
# uso str.replace('mg', '') para eliminar el texto 'mg'
# esto deja solo el número en valores como '100mg'

# convierto la columna a tipo numérico
prescripciones['dosis_mg'] = pd.to_numeric(prescripciones['dosis_mg'], errors='coerce')
# uso pd.to_numeric para convertir los valores a números
# uso errors='coerce' para que los valores que no se puedan convertir pasen a NaN
# esto es importante porque hay valores mezclados o inválidos

In [1000]:
# reviso los valores únicos después de la limpieza
prescripciones['dosis_mg'].unique()
# esto me permite confirmar que ya no hay strings como '100mg'

array([  250.,   400.,   200.,   500.,   850.,    nan,   100.,  1000.,
        -500.,  -200.,  -850.,  -100., 50000.,  -250.,  -400., -1000.])

In [1001]:
# convierto la columna a tipo numérico
prescripciones['dosis_mg'] = pd.to_numeric(prescripciones['dosis_mg'], errors='coerce')
# uso pd.to_numeric para convertir los valores a números reales
# uso errors='coerce' para que valores no válidos se conviertan en NaN
# esto asegura que la columna quede lista para análisis matemático

prescripciones['dosis_mg'].info()
#reviso que si quedara convertida a formato numerico

<class 'pandas.core.series.Series'>
RangeIndex: 520 entries, 0 to 519
Series name: dosis_mg
Non-Null Count  Dtype  
--------------  -----  
488 non-null    float64
dtypes: float64(1)
memory usage: 4.2 KB


In [1002]:
# identifico valores negativos en la dosis
prescripciones[prescripciones['dosis_mg'] < 0]
# uso esta condición para ver si existen dosis negativas
# esto me ayuda a entender si hay errores en los datos

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
28,9211,2023-06-03,METFORMINA,-500.0,subcutanea,J06.9,77.391128,34.0,Sanitas,MED-6383
31,4473,2025-02-11,ibuprofeno,-200.0,oral,hipertension,69.258523,40.0,nueva eps,MED-1053
43,9395,2025-04-19,Metformina 500,-850.0,Oral,E11,55.403989,29.0,nueva eps,NaN
72,6527,2025-11-29,METFORMINA,-100.0,Subcutanea,NaN,78.943714,32.0,Compensar,MED-5526
127,3829,2025-11-30,Metformina 500,-500.0,Subcutanea,NaN,74.652371,48.0,Sura,MED-5114
188,4165,2023-11-29,Enalapril,-250.0,IV,diabetes tipo 2,65.282456,21.0,EPS Sanitas,MED-0709
218,2973,2023-10-11,amoxicilina,-850.0,Intravenosa,K29.5,46.159876,73.0,EPS Sanitas,MED-8448
231,3358,2024-02-19,ASA,-400.0,Intravenosa,E11,77.312153,21.0,COMPENSAR,MED-3286
361,7457,2025-08-04,Aspirina,-1000.0,Oral,NaN,57.269915,34.0,Nueva EPS,MED-5259
365,9565,2024-10-27,Ibuprofeno,-500.0,SC,Z00.0,53.331800,32.0,Sanitas,MED-8185


In [1003]:
# convierto valores negativos en NaN
prescripciones.loc[prescripciones['dosis_mg'] < 0, 'dosis_mg'] = np.nan
# uso loc para modificar solo las filas donde la condición se cumple
# uso la condición < 0 para detectar valores negativos
# los convierto en NaN porque una dosis negativa no tiene sentido clínico
# esto evita usar datos erróneos en el análisis

In [1004]:
# cuento cuántos valores nulos hay en la columna dosis_mg
prescripciones['dosis_mg'].isnull().sum()
# uso ['dosis_mg'] para trabajar solo con esa columna
# uso isnull() para identificar los valores que son NaN (True si es nulo)
# uso sum() porque True cuenta como 1, entonces me da el total de valores nulos

np.int64(44)

In [1005]:
# calculo el porcentaje de valores nulos en dosis_mg
prescripciones['dosis_mg'].isnull().mean() * 100
# uso mean() porque calcula la proporción de valores nulos
# multiplico por 100 para pasarlo a porcentaje

np.float64(8.461538461538462)

In [1006]:
# reviso los valores únicos de la columna medicamento
prescripciones['medicamento'].unique()
# uso ['medicamento'] para trabajar solo con esa columna
# uso unique() para ver todos los nombres diferentes que hay
# esto me ayuda a notar que el mismo medicamento aparece escrito de varias formas
# por ejemplo en mayúsculas, minúsculas o con espacios diferentes
# esto es importante porque más adelante al usar groupby cada variación se toma como un grupo distinto
# entonces aquí ya identifico que esa columna también necesita limpieza en el siguiente punto

array(['ENALAPRIL', 'ASA', 'Enalapril', 'METFORMINA', 'metformina',
       'Amoxicilina', 'Ibuprofeno ', 'amoxicilina', 'ibuprofeno',
       'Aspirina ', 'Metformina 500'], dtype=object)

In [1007]:
# relleno los valores faltantes de dosis usando la mediana por medicamento
prescripciones['dosis_mg'] = prescripciones['dosis_mg'].fillna(
    prescripciones.groupby('medicamento')['dosis_mg'].transform('median')
)
# uso groupby('medicamento') para agrupar los datos por tipo de medicamento
# esto me permite calcular valores dentro de cada grupo
# uso transform('median') para calcular la mediana de dosis dentro de cada medicamento
# uso fillna() para reemplazar los valores que están como NaN
# esto me permite no eliminar datos sino completarlos con un valor representativo

# reviso cuántos valores siguen como NaN después de rellenar
prescripciones['dosis_mg'].isnull().sum()
# esto me permite confirmar si ya se completaron los valores faltantes

np.int64(0)

In [1008]:
# reviso valores muy altos en dosis
prescripciones[prescripciones['dosis_mg'] == 1000]
# uso esta condición para analizar manualmente estos casos y no asumir de una vez que son errores
# al principio pensé que 1000 mg podía ser un valor fuera de rango, pero investigando entendí que no necesariamente
# por ejemplo, en medicamentos como metformina o amoxicilina sí pueden existir dosis de 1000 mg dependiendo del tratamiento
# en el caso de ibuprofeno, aunque es menos común en una sola toma, tampoco se puede descartar completamente sin más contexto clínico
# esto me llevó a no tomar decisiones apresuradas sobre estos valores

# además, observé que en la columna medicamento aparecen valores como "metformina 500",
# lo que puede indicar la presentación del medicamento (por ejemplo tabletas de 500 mg),
# y si en dosis_mg aparece 1000, podría significar que el paciente está tomando dos tabletas,
# o también podría ser un error, pero con la información disponible no se puede asegurar

# por esta razón decidí NO marcar como inválidos los valores de 1000 mg,
# ya que el dataset no tiene suficiente información clínica (frecuencia, duración, unidad exacta, etc.)
# para determinar si son correctos o no

# en cambio, el criterio que utilicé fue identificar valores claramente extremos como 50000 mg,
# los cuales sí son poco realistas en miligramos y pueden indicar errores de digitación o confusión de unidades (por ejemplo UI vs mg)

# con esto, busco no eliminar información potencialmente válida,
# sino diferenciar entre valores dudosos (como 1000 mg) y valores claramente no confiables (como 50000 mg)

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
25,7400,2024-03-17,Ibuprofeno,1000.0,VO,I10,80.841322,71.0,Compensar,MED-3055
26,2488,2024-12-29,Metformina 500,1000.0,via oral,E11,69.034482,71.0,SURA,MED-4864
27,9826,2024-01-08,Amoxicilina,1000.0,oral,I10,72.938674,75.0,Nueva EPS,MED-4211
30,2215,2026-04-23,METFORMINA,1000.0,Intravenosa,hipertension,58.155356,40.0,Compensar,MED-0731
47,9619,2023-09-17,METFORMINA,1000.0,Subcutanea,Z00.0,60.258824,24.0,SANITAS,MED-0493
52,7032,2024-03-29,Metformina 500,1000.0,Intravenosa,J18.9,NaN,30.0,nueva eps,MED-4061
58,6194,2026-03-28,metformina,1000.0,Intravenosa,E11,56.945923,70.0,NuevaEPS,MED-9037
62,3616,2024-08-21,METFORMINA,1000.0,SC,K29.5,52.639610,34.0,Sura,MED-3086
66,9617,2024-11-25,ASA,1000.0,SC,diabetes tipo 2,71.742360,58.0,SURA,MED-1276
92,1336,2025-12-18,ibuprofeno,1000.0,IV,K29.5,2.000000,69.0,SANITAS,MED-2633


In [1009]:
# reviso valores muy altos en dosis
prescripciones[prescripciones['dosis_mg'] > 5000]
# uso esta condición para identificar dosis que parecen poco realistas
# esto me ayuda a ver si hay errores grandes en la columna

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
80,7332,2024-07-21,ENALAPRIL,50000.0,Subcutanea,diabetes tipo 2,65.139389,18.0,Nueva EPS,MED-9971
263,8584,2025-06-23,Metformina 500,50000.0,via oral,K29.5,67.134475,51.0,NuevaEPS,MED-4986
296,6235,2023-09-16,ibuprofeno,50000.0,Oral,J06.9,76.725212,42.0,Sanitas,MED-0303
445,3401,2023-07-04,ASA,50000.0,oral,E11,64.570679,43.0,Compensar,MED-4031
486,1594,2026-04-07,amoxicilina,50000.0,intravenosa,Z00.0,63.690292,73.0,SANITAS,MED-2916


In [1010]:
# convierto valores demasiado altos en NaN
prescripciones.loc[prescripciones['dosis_mg'] > 5000, 'dosis_mg'] = np.nan
# uso loc para modificar solo esas filas
# uso > 5000 como criterio para detectar valores fuera de rango
# los convierto en NaN porque no son valores confiables
# uso np.nan porque estos valores están mal, no son confiables, así que los convierto en dato faltante

In [1011]:
# vuelvo a rellenar los NaN después de eliminar outliers
prescripciones['dosis_mg'] = prescripciones['dosis_mg'].fillna(
    prescripciones.groupby('medicamento')['dosis_mg'].transform('median')
)
# esto me permite completar los datos que convertí en NaN con valores representativos
# uso groupby('medicamento') para agrupar los datos por tipo de medicamento
# esto me permite calcular valores dentro de cada grupo
# uso transform('median') para calcular la mediana de dosis dentro de cada medicamento
# uso fillna() para reemplazar los valores que están como NaN
# esto me permite no eliminar datos sino completarlos con un valor representativo

# reviso cuántos valores siguen como NaN después de rellenar
prescripciones['dosis_mg'].isnull().sum()
# esto me permite confirmar si ya se completaron los valores faltantes

np.int64(0)

In [1012]:
# reviso los valores únicos después de la limpieza
prescripciones['dosis_mg'].unique()

array([ 250.,  400.,  200.,  500.,  850.,  100., 1000.])

In [1013]:
# verifico que ya no hay valores extremos en la columna dosis_mg
prescripciones[prescripciones['dosis_mg'] > 5000]
# uso esta condición para confirmar que ya no existen valores fuera de rango

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id


In [1014]:
# reviso estadísticas finales de la columna
prescripciones['dosis_mg'].describe()
# esto me permite ver si los valores tienen sentido después de la limpieza

,dosis_mg
count,520.000000
mean,425.480769
std,289.973355
min,100.000000
25%,200.000000
50%,400.000000
75%,500.000000
max,1000.000000


In [1015]:
prescripciones.head(20)
#reviso como se va viendo la tabla

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
0,4355,2024-03-08,ENALAPRIL,250.0,VO,K29.5,79.586599,72.0,Compensar,MED-2771
1,4442,2023-09-03,ASA,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,NuevaEPS,MED-9403
2,8015,2026-04-10,Enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN
3,4887,2026-01-19,METFORMINA,500.0,subcutanea,hipertension,85.277837,NaN,COMPENSAR,MED-4463
4,1406,2024-06-18,metformina,250.0,IV,NaN,71.785582,47.0,Nueva EPS,MED-5819
5,7309,2026-03-24,Amoxicilina,850.0,Oral,Z00.0,63.396508,67.0,Sura,NaN
6,4337,2026-01-26,Ibuprofeno,200.0,via oral,E11,85.457759,23.0,COMPENSAR,MED-8594
7,9589,2025-06-29,Ibuprofeno,250.0,IV,NaN,83.736521,34.0,EPS Sanitas,MED-7444
8,2976,2024-08-26,Enalapril,250.0,Oral,K29.5,39.603594,63.0,SANITAS,MED-8023
9,2647,2024-10-16,Ibuprofeno,250.0,IV,diabetes tipo 2,78.122144,64.0,SANITAS,NaN


In [1016]:
# guardo el dataset después de limpiar la columna dosis_mg
prescripciones_avance = prescripciones.copy()
# uso copy() para guardar el estado actual del dataframe
# esto me permite no perder lo que ya hice en este punto
# así en el siguiente punto puedo seguir desde aquí sin volver al dataset original

#**Markdown**

Profe, en este punto trabajé la limpieza de la columna dosis_mg, donde encontré varios problemas importantes que no eran solo técnicos sino también de interpretación de datos clínicos.

Primero revisé los valores únicos de la columna y me di cuenta que venían mezclados: había números como texto ('250.0'), valores con unidades ('100mg', '500mg'), valores negativos (-500, -1000) e incluso valores extremadamente altos como 50000. Esto me permitió entender que no podía trabajar directamente la columna sin antes transformarla.

Lo primero que hice fue extraer solo la parte numérica de los valores, quitando el texto como “mg”, y luego convertí toda la columna a tipo numérico. Esto era necesario porque más adelante necesito hacer cálculos y análisis, y en tipo object no se puede trabajar bien.

Después de eso me enfoqué en los valores negativos. Aquí fue donde me detuve a pensar más en el criterio, porque no es solo limpiar por limpiar. En un contexto real de salud, una dosis negativa no tiene sentido clínico, no representa un valor válido sino un error en el registro. Por esa razón decidí convertir todos los valores negativos en NaN, en lugar de eliminarlos directamente, porque el dato sigue representando que hubo una prescripción pero con un valor incorrecto.

Luego revisé los valores extremadamente altos. Al principio dudé, porque investigando vi que sí existen medicamentos de 1000 mg, lo cual es normal en muchos tratamientos. Pero también encontré valores como 50000, y ahí entendí que probablemente hay confusión entre unidades (por ejemplo UI vs mg) o errores de digitación. Por eso tomé como criterio considerar como válidos valores hasta 1000 mg y convertir a NaN los que estuvieran por encima de ese rango, ya que no son realistas para este tipo de variable en mg.

Después de esto tenía varios valores faltantes (los originales más los que convertí desde negativos y outliers). En lugar de eliminarlos, decidí completarlos usando la mediana por medicamento. Esta parte me costó entenderla al inicio, porque no entendía bien qué significaba “imputar”, pero ya vi que se trata de reemplazar valores faltantes con un valor representativo.

lo hice como pidio con  la mediana y transform y además lo hice agrupando por medicamento, ya que cada medicamento tiene dosis diferentes y no tendría sentido usar un solo valor para todos. Así logro mantener coherencia clínica dentro de cada grupo.

Finalmente verifiqué que ya no quedaran valores nulos y revisé nuevamente los valores únicos y estadísticas. La columna quedó con valores coherentes (entre 100 y 1000 mg), sin datos negativos, sin strings y sin valores extremos fuera de rango.

Algo importante en este proceso es que intenté no eliminar información innecesariamente, sino corregirla o completarla de la forma más razonable posible, por ejemplo, en este punto revisé específicamente los valores de 1000 mg porque al inicio pensé que podían ser errores, pero al analizar mejor entendí que no necesariamente son inválidos. Investigando y viendo el contexto, noté que para algunos medicamentos como metformina o amoxicilina sí pueden existir dosis de 1000 mg dependiendo del tratamiento, y en otros casos como ibuprofeno no se puede descartar completamente sin más información clínica. Además, observé que aparecen valores como “metformina 500” en la columna de medicamento, lo que puede indicar la presentación (por ejemplo tabletas de 500 mg), por lo que una dosis de 1000 mg podría corresponder a la toma de dos unidades. Debido a que el dataset no incluye información suficiente como frecuencia o indicación médica, decidí no clasificar estos valores como errores. En cambio, enfoqué el criterio en identificar valores claramente extremos como 50000 mg, que sí son poco realistas en miligramos y probablemente representan errores de digitación o confusión de unidades.

#*******************************************************************************************************************

6. Normalice medicamento y via_administracion: elimine espacios, convierta a minúsculas y
construya un diccionario de mapeo para unificar equivalentes (por ejemplo, 'VO', 'oral',
'Oral', 'via oral' deben converger en una forma canónica).

In [1017]:
# recupero el dataset desde el avance anterior
prescripciones = prescripciones_avance.copy()
# uso copy() para seguir trabajando desde el dataset que ya tiene fechas y dosis limpias
# esto evita perder el trabajo que ya hice en los puntos anteriores

In [1018]:
# reviso los valores únicos de medicamento antes de limpiar
prescripciones['medicamento'].unique()
# uso unique() para ver todas las formas diferentes en que aparece cada medicamento
# esto me ayuda a identificar mayúsculas, minúsculas, espacios o nombres equivalentes

array(['ENALAPRIL', 'ASA', 'Enalapril', 'METFORMINA', 'metformina',
       'Amoxicilina', 'Ibuprofeno ', 'amoxicilina', 'ibuprofeno',
       'Aspirina ', 'Metformina 500'], dtype=object)

In [1019]:
# reviso los valores únicos de via_administracion antes de limpiar
prescripciones['via_administracion'].unique()
# uso unique() para ver todas las formas diferentes en que aparece la vía de administración
# esto me ayuda a identificar valores equivalentes como VO, oral, Oral y via oral

array(['VO', 'subcutanea', 'intravenosa', 'IV', 'Oral', 'via oral', 'SC',
       'oral', 'Intravenosa', 'Subcutanea'], dtype=object)

In [1020]:
# limpio la columna medicamento quitando espacios y pasando todo a minúsculas como el docente lo pide
prescripciones['medicamento'] = prescripciones['medicamento'].str.strip().str.lower()
# uso str.strip() para quitar espacios al inicio o al final del texto
# uso str.lower() para convertir todo a minúsculas
# esto me ayuda a que valores como ENALAPRIL y Enalapril queden escritos igual
#no puse .srt.title() aunque queria porque el docente no pidio la primera en mayuscula, pero tuve toda la intencion

prescripciones['medicamento'].unique()
#verifico como quedaron

array(['enalapril', 'asa', 'metformina', 'amoxicilina', 'ibuprofeno',
       'aspirina', 'metformina 500'], dtype=object)

In [1021]:
# limpio la columna via_administracion quitando espacios y pasando todo a minúsculas
prescripciones['via_administracion'] = prescripciones['via_administracion'].str.strip().str.lower()
# uso str.strip() para quitar espacios sobrantes
# uso str.lower() para dejar todo en minúsculas
# esto me ayuda a comparar mejor las categorías y reducir diferencias por escritura
#no puse .srt.title() aunque queria porque el docente no pidio la primera en mayuscula, pero tuve toda la intencion

prescripciones['via_administracion'].unique()
#verifico como quedaron

array(['vo', 'subcutanea', 'intravenosa', 'iv', 'oral', 'via oral', 'sc'],
      dtype=object)

In [1022]:
# creo un diccionario para unificar nombres de medicamentos
mapa_medicamentos = {
    'enalapril': 'enalapril',
    'asa': 'asa',
    'metformina': 'metformina',
    'metformina 500': 'metformina',
    'amoxicilina': 'amoxicilina',
    'ibuprofeno': 'ibuprofeno',
    'aspirina': 'aspirina'
}
# uso un diccionario porque quiero indicar cómo debe quedar escrito cada medicamento
# por ejemplo metformina 500 la dejo como metformina porque realmente pertenece al mismo medicamento
# esto me ayuda a reducir categorías repetidas o mal escritas

In [1023]:
# aplico el diccionario a la columna medicamento
prescripciones['medicamento'] = prescripciones['medicamento'].replace(mapa_medicamentos)
# uso replace() para cambiar los valores según el diccionario que construí
# esto me permite dejar los medicamentos en una forma más ordenada y estándar

In [1024]:
# reviso los valores únicos de medicamento después de la limpieza
prescripciones['medicamento'].unique()
# esto me permite confirmar que las categorías quedaron más ordenadas

array(['enalapril', 'asa', 'metformina', 'amoxicilina', 'ibuprofeno',
       'aspirina'], dtype=object)

In [1025]:
# reviso cuántas categorías diferentes quedaron en medicamento
prescripciones['medicamento'].nunique()
# uso nunique() para contar cuántos valores únicos quedan después de la limpieza
# esto me permite medir si reduje la cardinalidad

6

In [1026]:
# creo un diccionario para unificar las vías de administración
mapa_vias = {
    'vo': 'oral',
    'oral': 'oral',
    'via oral': 'oral',
    'iv': 'intravenosa',
    'intravenosa': 'intravenosa',
    'sc': 'subcutanea',
    'subcutanea': 'subcutanea'
}
# uso este diccionario porque hay varias formas de escribir la misma vía
# por ejemplo VO, oral y via oral significan lo mismo y las dejo como oral
# también IV la dejo como intravenosa y SC como subcutanea

In [1027]:
# aplico el diccionario a la columna via_administracion
prescripciones['via_administracion'] = prescripciones['via_administracion'].replace(mapa_vias)
# uso replace() para unificar las vías según el diccionario
# esto me ayuda a reducir categorías y dejar una sola forma canónica por cada vía

# reviso los valores únicos de via_administracion después de la limpieza
prescripciones['via_administracion'].unique()
# esto me permite confirmar que las vías equivalentes quedaron unificadas

array(['oral', 'subcutanea', 'intravenosa'], dtype=object)

In [1028]:
# reviso cuántas categorías diferentes quedaron en via_administracion
prescripciones['via_administracion'].nunique()
# uso nunique() para contar cuántas vías diferentes quedaron
# esto me ayuda a confirmar si la normalización funcionó

3

In [1029]:
prescripciones.head(20)
#reviso como se va viendo la tabla

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
0,4355,2024-03-08,enalapril,250.0,oral,K29.5,79.586599,72.0,Compensar,MED-2771
1,4442,2023-09-03,asa,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,NuevaEPS,MED-9403
2,8015,2026-04-10,enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN
3,4887,2026-01-19,metformina,500.0,subcutanea,hipertension,85.277837,NaN,COMPENSAR,MED-4463
4,1406,2024-06-18,metformina,250.0,intravenosa,NaN,71.785582,47.0,Nueva EPS,MED-5819
5,7309,2026-03-24,amoxicilina,850.0,oral,Z00.0,63.396508,67.0,Sura,NaN
6,4337,2026-01-26,ibuprofeno,200.0,oral,E11,85.457759,23.0,COMPENSAR,MED-8594
7,9589,2025-06-29,ibuprofeno,250.0,intravenosa,NaN,83.736521,34.0,EPS Sanitas,MED-7444
8,2976,2024-08-26,enalapril,250.0,oral,K29.5,39.603594,63.0,SANITAS,MED-8023
9,2647,2024-10-16,ibuprofeno,250.0,intravenosa,diabetes tipo 2,78.122144,64.0,SANITAS,NaN


In [1030]:
# guardo el avance después de normalizar medicamento y via_administracion
prescripciones_avance = prescripciones.copy()
# uso copy() para guardar el dataset con fechas, dosis, medicamento y via_administracion ya limpios
# esto me permite seguir al siguiente punto sin perder lo que ya hice

#**Markdown**

En este punto trabajé la normalización de las columnas medicamento y via_administracion, porque al revisar los valores únicos me di cuenta que había muchas formas distintas de escribir lo mismo. Por ejemplo, en medicamento aparecían cosas como “ENALAPRIL”, “Enalapril”, “metformina”, “METFORMINA” e incluso “Metformina 500”, y en la vía de administración salían valores como “VO”, “oral”, “Oral”, “via oral”, “IV”, “intravenosa”, “SC”, “subcutanea”, entre otros. Entonces aquí el problema claramente era de inconsistencia categórica, porque una misma categoría estaba representada de varias maneras.

Lo primero que hice fue una limpieza básica del texto usando .str.strip() para quitar espacios y .str.lower() para dejar todo en minúsculas. Esto me ayudó a unificar muchas diferencias que eran solo por forma de escritura, por ejemplo que “ENALAPRIL” y “Enalapril” quedaran iguales. No usé .title() aunque lo pensé, porque el docente no lo pidió y preferí mantener todo en minúsculas para evitar inconsistencias.

Luego construí diccionarios de mapeo para ambas columnas. En medicamento los usé para dejar una sola forma correcta por cada medicamento, y en la vía de administración los usé para unificar equivalentes, por ejemplo dejar “vo”, “oral” y “via oral” simplemente como “oral”, “iv” como “intravenosa” y “sc” como “subcutanea”. Esto lo hice porque en un análisis real no tiene sentido contar esas variantes como cosas diferentes si representan exactamente lo mismo.

Después de aplicar estos cambios volví a revisar los valores únicos y pude ver que las categorías quedaron mucho más organizadas. En medicamento logré reducirlas a 6 categorías claras, y en vía de administración a 3, lo cual muestra que sí se redujo la cardinalidad como pedía el punto. Esto es importante porque facilita cualquier análisis posterior y evita errores al agrupar o contar datos.

Este punto fue más claro que los anteriores, pero igual me tocó estar pendiente de detalles, sobre todo revisar bien los valores únicos porque fue ahí donde detecté cosas como “metformina 500”, que fácilmente se me podía pasar y afectar el análisis.

#*******************************************************************************************************************

7. Detecte y trate outliers en peso_paciente_kg usando el método del rango intercuartílico
(IQR). Decida entre eliminar o imputar y justifique. Muestre la distribución antes y después
con .describe().

In [1031]:
# reviso estadísticas iniciales de la columna peso_paciente_kg
prescripciones['peso_paciente_kg'].describe()
# uso ['peso_paciente_kg'] para seleccionar solo la columna que voy a analizar
# uso describe() porque me muestra medidas como mínimo, máximo, media y cuartiles
# esto me ayuda a entender cómo están distribuidos los pesos
# también me permite detectar valores sospechosos como 2 kg o 600 kg antes de aplicar cualquier método


,peso_paciente_kg
count,500.000000
mean,69.686264
std,36.587824
min,2.000000
25%,59.690991
50%,67.420535
75%,75.949301
max,600.000000


In [1032]:
#reviso como se ve
prescripciones.head()

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
0,4355,2024-03-08,enalapril,250.0,oral,K29.5,79.586599,72.0,Compensar,MED-2771
1,4442,2023-09-03,asa,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,NuevaEPS,MED-9403
2,8015,2026-04-10,enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN
3,4887,2026-01-19,metformina,500.0,subcutanea,hipertension,85.277837,NaN,COMPENSAR,MED-4463
4,1406,2024-06-18,metformina,250.0,intravenosa,NaN,71.785582,47.0,Nueva EPS,MED-5819


In [1033]:
# calculo el primer cuartil (Q1)
q1 = prescripciones['peso_paciente_kg'].quantile(0.25)
# uso quantile(0.25) para obtener el valor por debajo del cual está el 25% de los datos
# esto me sirve como base para calcular el rango intercuartílico


# calculo el tercer cuartil (Q3)
q3 = prescripciones['peso_paciente_kg'].quantile(0.75)
# uso quantile(0.75) para obtener el valor por debajo del cual está el 75% de los datos
# esto me ayuda a identificar el rango donde están la mayoría de los datos normales

In [1034]:
# calculo el rango intercuartílico (IQR)
iqr = q3 - q1
# el IQR representa la diferencia entre Q3 y Q1
# esto mide la dispersión de los datos centrales y es la base para detectar outliers


# defino el límite inferior para detectar outliers bajos
limite_inferior = q1 - 1.5 * iqr
# uso la fórmula Q1 - 1.5*IQR porque es el criterio estándar del método IQR
# esto me permite identificar valores demasiado bajos que no siguen la distribución normal


# defino el límite superior para detectar outliers altos
limite_superior = q3 + 1.5 * iqr
# uso la fórmula Q3 + 1.5*IQR para detectar valores demasiado altos
# esto me ayuda a encontrar posibles errores como pesos extremadamente altos

In [1035]:
# identifico los registros que quedaron por fuera de los límites del IQR
outliers_peso = prescripciones[
    (prescripciones['peso_paciente_kg'] < limite_inferior) |
    (prescripciones['peso_paciente_kg'] > limite_superior)
]
# uso esta condición para guardar los pesos que el método IQR detecta como posibles outliers
# esto me permite revisarlos antes de decidir si los elimino, los imputo o los dejo

In [1036]:
# cuento cuántos valores quedaron como NaN después del tratamiento
prescripciones['peso_paciente_kg'].isnull().sum()
# uso isnull() para identificar los valores que están como NaN (True si es nulo)
# uso sum() porque True cuenta como 1 y False como 0, entonces obtengo el total de nulos
# esto me permite saber cuántos datos fueron afectados por el tratamiento de outliers

np.int64(20)

In [1037]:
# reviso los registros detectados como outliers junto con la edad
outliers_peso[['peso_paciente_kg', 'edad']]
# uso [['col1','col2']] para seleccionar varias columnas y analizarlas juntas
# esto me permite ver si el peso tiene sentido según la edad del paciente
# por ejemplo, un peso de 2 kg con una edad de 60 años es claramente un error

,peso_paciente_kg,edad
16,101.395089,56.0
18,3.000000,48.0
33,450.000000,36.0
92,2.000000,69.0
177,3.000000,70.0
178,2.000000,62.0
278,2.000000,18.0
285,2.000000,71.0
319,600.000000,36.0
335,450.000000,83.0


In [1038]:
# convierto en NaN solamente los pesos claramente imposibles
prescripciones.loc[
    (prescripciones['peso_paciente_kg'] <= 3) |
    (prescripciones['peso_paciente_kg'] >= 250),
    'peso_paciente_kg'
] = np.nan

# uso loc para modificar solo las filas que cumplen esta condición
# uso <= 3 porque pesos de 2 o 3 kg no tienen sentido en pacientes adultos o jóvenes
# uso >= 250 porque pesos como 450 o 600 kg son demasiado extremos y no son confiables
# no elimino la fila completa porque en salud perdería información del paciente
# tampoco modifico valores como 101 kg, 34 kg o 33 kg porque aunque son extremos, sí pueden ser reales

In [1039]:
# miro los registros donde peso_paciente_kg quedó como NaN para analizarlos
nan_peso = prescripciones[prescripciones['peso_paciente_kg'].isnull()]
# uso isnull() para filtrar solo los registros donde el peso quedó como NaN
# esto me permite enfocarme únicamente en los valores que debo corregir

# reviso esas filas con variables importantes
nan_peso[['edad', 'peso_paciente_kg']]
# selecciono edad porque el peso depende directamente de esta variable
# esto me ayuda a entender si puedo imputar usando grupos de edad
# esto me permite ver si hay algún patrón adicional en los datos
# por ejemplo si ciertos errores se repiten en algún tipo de paciente


,edad,peso_paciente_kg
12,68.0,NaN
18,48.0,NaN
20,60.0,NaN
33,36.0,NaN
35,83.0,NaN
52,30.0,NaN
65,48.0,NaN
92,69.0,NaN
99,18.0,NaN
102,-1.0,NaN


In [1040]:
# creo grupos de edad para poder rellenar el peso usando pacientes con edades parecidas
prescripciones['grupo_edad_peso'] = pd.cut(
    prescripciones['edad'],
    bins=[0, 30, 50, 70, 120],
    labels=['18-30', '31-50', '51-70', '71-120']
)
# uso pd.cut() porque me permite dividir una variable numérica en rangos
# uso la columna edad porque el peso se relaciona más con la edad que con medicamento o diagnóstico
# uso bins para definir los cortes de los grupos de edad
# el primer grupo toma edades mayores a 0 y hasta 30
# el segundo grupo toma edades mayores a 30 y hasta 50
# el tercero toma edades mayores a 50 y hasta 70
# el cuarto toma edades mayores a 70 y hasta 120
# uso labels para poner nombres claros a cada grupo
# esto me ayuda a no usar una sola mediana para todos los pacientes

# reviso cuántos pacientes quedaron en cada grupo de edad
prescripciones['grupo_edad_peso'].value_counts().sort_index()
# uso value_counts() para contar cuántos registros hay en cada grupo
# uso sort_index() para mostrar los grupos en orden
# esto me permite verificar que los grupos sí se crearon correctamente

,count
grupo_edad_peso,
18-30,95
31-50,147
51-70,159
71-120,95


In [1041]:
# reviso los pacientes que tienen peso faltante y el grupo de edad donde quedaron
prescripciones[prescripciones['peso_paciente_kg'].isnull()][
    ['edad', 'grupo_edad_peso', 'peso_paciente_kg']
]
# uso isnull() para filtrar solo los pesos que siguen como NaN
# muestro edad para confirmar que son edades válidas
# muestro grupo_edad_peso para saber con qué grupo se va a rellenar cada peso
# muestro peso_paciente_kg para verificar que esos son los datos pendientes por completar

,edad,grupo_edad_peso,peso_paciente_kg
12,68.0,51-70,NaN
18,48.0,31-50,NaN
20,60.0,51-70,NaN
33,36.0,31-50,NaN
35,83.0,71-120,NaN
52,30.0,18-30,NaN
65,48.0,31-50,NaN
92,69.0,51-70,NaN
99,18.0,18-30,NaN
102,-1.0,NaN,NaN


In [1042]:
# creo grupos de edad para poder rellenar el peso usando pacientes con edades parecidas
# Este bloque es añadido para asegurar que 'grupo_edad_peso' exista, en caso de ejecuciones fuera de orden.
if 'grupo_edad_peso' not in prescripciones.columns:
    prescripciones['grupo_edad_peso'] = pd.cut(
        prescripciones['edad'],
        bins=[0, 30, 50, 70, 120],
        labels=['18-30', '31-50', '51-70', '71-120']
    )

# relleno los valores faltantes de peso usando la mediana por grupo de edad
prescripciones['peso_paciente_kg'] = prescripciones['peso_paciente_kg'].fillna(
    prescripciones.groupby('grupo_edad_peso')['peso_paciente_kg'].transform('median')
)
# uso groupby('grupo_edad_peso') para agrupar pacientes por rangos de edad
# uso ['peso_paciente_kg'] para trabajar solo con esa columna
# uso transform('median') para calcular la mediana dentro de cada grupo
# uso fillna() para reemplazar únicamente los valores faltantes
# esto permite asignar un peso coherente según la edad del paciente
# así no uso una sola mediana para todos, sino una específica por grupo


# verifico que ya no queden NaN en peso
prescripciones['peso_paciente_kg'].isnull().sum()
# esto me permite confirmar si ya se completaron los valores faltantes


# elimino la columna auxiliar de grupos de edad
# Asegurarse de que la columna exista antes de intentar eliminarla
if 'grupo_edad_peso' in prescripciones.columns:
    prescripciones = prescripciones.drop(columns=['grupo_edad_peso'])
# elimino esta columna porque solo era una herramienta temporal
# no debe quedar en el dataset final

prescripciones.head(20)
#verifico que solo hubiera tocado los dataset NaN pues es mi unico objetivo

/tmp/ipykernel_7811/230937480.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  prescripciones.groupby('grupo_edad_peso')['peso_paciente_kg'].transform('median')


,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
0,4355,2024-03-08,enalapril,250.0,oral,K29.5,79.586599,72.0,Compensar,MED-2771
1,4442,2023-09-03,asa,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,NuevaEPS,MED-9403
2,8015,2026-04-10,enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN
3,4887,2026-01-19,metformina,500.0,subcutanea,hipertension,85.277837,NaN,COMPENSAR,MED-4463
4,1406,2024-06-18,metformina,250.0,intravenosa,NaN,71.785582,47.0,Nueva EPS,MED-5819
5,7309,2026-03-24,amoxicilina,850.0,oral,Z00.0,63.396508,67.0,Sura,NaN
6,4337,2026-01-26,ibuprofeno,200.0,oral,E11,85.457759,23.0,COMPENSAR,MED-8594
7,9589,2025-06-29,ibuprofeno,250.0,intravenosa,NaN,83.736521,34.0,EPS Sanitas,MED-7444
8,2976,2024-08-26,enalapril,250.0,oral,K29.5,39.603594,63.0,SANITAS,MED-8023
9,2647,2024-10-16,ibuprofeno,250.0,intravenosa,diabetes tipo 2,78.122144,64.0,SANITAS,NaN


In [1043]:
# reviso los pacientes que  me queda  y tienen peso faltante y el grupo de edad donde quedaron
prescripciones[prescripciones['peso_paciente_kg'].isnull()][
    ['edad', 'peso_paciente_kg']
]
# uso isnull() para filtrar solo los pesos que siguen como NaN
# muestro edad para confirmar que son edades válidas
# muestro grupo_edad_peso para saber con qué grupo se va a rellenar cada peso
# muestro peso_paciente_kg para verificar que esos son los datos pendientes por completar

,edad,peso_paciente_kg
102,-1.0,NaN
229,200.0,NaN
355,NaN,NaN
433,0.0,NaN


In [1044]:
# elimino los registros donde no es posible imputar el peso
indices_eliminar = [102, 229, 355, 433]
# uso una lista con los índices que identifiqué manualmente
# estos casos tienen edad inválida (-1, 0, 200) o edad NaN
# y además el peso también está como NaN
# esto significa que no tengo ninguna base para estimar el peso de forma coherente

# elimino esos registros específicos del dataframe
prescripciones = prescripciones.drop(indices_eliminar)
# uso drop() para eliminar solo estas filas puntuales
# no uso dropna() porque eso eliminaría datos de forma general sin análisis previo
# aquí la eliminación es controlada y justificada según el contexto clínico

# verifico que ya no existan esos registros
prescripciones[prescripciones.index.isin(indices_eliminar)]
# uso isin() para comprobar si alguno de esos índices sigue en el dataframe
# si no aparece nada, significa que se eliminaron correctamente


# reviso nuevamente cuántos valores NaN quedan en peso
prescripciones['peso_paciente_kg'].isnull().sum()
# uso isnull() para identificar los pesos que siguen como NaN
# uso sum() para contar cuántos quedan
# esto me permite confirmar que ya eliminé los casos que no se podían tratar

np.int64(0)

In [1045]:

# reviso cuáles registros siguen teniendo peso faltante
prescripciones[prescripciones['peso_paciente_kg'].isnull()][['edad', 'peso_paciente_kg']]
# muestro edad y peso para verificar que ahora sí todos los casos restantes
# tienen edad válida y se pueden imputar usando los grupos de edad

,edad,peso_paciente_kg


In [1046]:
# reviso estadísticas finales de la columna peso_paciente_kg
prescripciones['peso_paciente_kg'].describe()
# uso ['peso_paciente_kg'] para seleccionar solo la columna que voy a analizar
# uso describe() porque me muestra medidas como mínimo, máximo, media y cuartiles
#finalmente mirar como quedo todo

,peso_paciente_kg
count,516.000000
mean,68.010904
std,11.189435
min,33.711230
25%,60.486002
50%,68.362171
75%,75.227430
max,101.395089


In [1047]:
# guardo el avance después de normalizar medicamento y via_administracion
prescripciones_avance = prescripciones.copy()
# uso copy() para guardar el dataset con fechas, dosis, medicamento y via_administracion ya limpios
# esto me permite seguir al siguiente punto sin perder lo que ya hice

#**Markdown**

En este punto profe, sinceramente fue donde más me detuve porque no quise hacerlo de forma automática sino entender qué estaba pasando con los datos. Primero revisé la distribución de peso_paciente_kg usando describe() y ahí noté valores que no tenían sentido, como pesos extremadamente bajos (2 o 3 kg en adultos) y otros demasiado altos (450 o 600 kg), lo que claramente indica errores en los datos.

Después de identificar estos posibles outliers con el criterio del rango intercuartílico (IQR), no tomé la decisión inmediata de eliminarlos o reemplazarlos, sino que revisé los registros uno por uno junto con la edad y otras variables. Esto me hizo darme cuenta de algo importante: no todos los outliers se pueden tratar igual, porque algunos tenían información suficiente para ser corregidos y otros no.

En los casos donde el peso era inválido pero la edad sí era coherente, decidí no eliminar esos registros, sino imputar el peso usando la mediana por grupos de edad. Esto lo hice porque el peso tiene relación con la edad, entonces me parecía más lógico asignar un valor basado en pacientes similares y no una mediana global para todos.

Sin embargo, encontré algunos casos donde tanto la edad como el peso eran inválidos o estaban faltantes (por ejemplo edades como -1, 0, 200 o incluso NaN junto con peso NaN). En estos casos sí tomé la decisión de eliminarlos, porque no existía ninguna base para imputar un valor confiable. Considero que inventar un valor en esos casos habría afectado la calidad del análisis.

También quiero aclarar que inicialmente había considerado no eliminar estos registros, pero al analizar mejor el contexto entendí que en estos casos específicos la eliminación era la decisión más coherente. Este proceso me tomó tiempo porque intenté varias alternativas antes de decidirme.

 después de aplicar estas decisiones, volví a usar describe() para verificar cómo quedó la distribución del peso, y ya se observa que los valores están en rangos mucho más realistas, sin extremos que distorsionen el análisis. Con esto considero que la limpieza de esta variable quedó correctamente realizada.

 Además de que me parecía lógico hacerlo así, también tomé esta decisión pensando en el contexto real de una empresa de salud. Como científica de datos, no se trata solo de completar datos por completar, sino de mantener la coherencia clínica de la información, porque estos datos pueden influir en análisis médicos, decisiones administrativas o incluso en modelos que afecten pacientes. Si yo hubiera usado una mediana global para todos los casos, estaría ignorando diferencias importantes entre pacientes jóvenes y adultos mayores, lo que podría generar conclusiones incorrectas. En cambio, al usar la mediana por grupos de edad, estoy respetando mejor la variabilidad natural del peso según la edad, lo que hace que los datos sean más realistas y útiles para la empresa. Esto ayuda a que cualquier análisis posterior, como segmentación de pacientes o estudios de tratamientos, tenga una base más confiable. Por otro lado, también fui cuidadosa en no imputar cuando no había información suficiente, porque inventar datos en un contexto clínico puede ser más perjudicial que útil, ya que podría introducir sesgos o errores en los resultados.

 durante el análisis también noté que había “huecos” difíciles de interpretar. Aunque usé la edad como referencia, soy consciente de que el peso de una persona no depende solo de eso. Puede haber pacientes con sobrepeso, bajo peso o condiciones como desnutrición, y eso no se puede inferir únicamente con la información disponible. También revisé variables como el medicamento y el diagnóstico, pero estos no daban señales claras sobre el peso del paciente; por ejemplo, medicamentos como la metformina están asociados a diabetes, y otros casos eran de hipertensión o condiciones cardíacas, pero nada de eso permite concluir si una persona es más pesada o más liviana. Por eso entendí que esta no era una decisión sencilla ni exacta, sino una aproximación basada en la mejor información disponible. Traté de ser lo más cuidadosa posible para no distorsionar los datos, aunque reconozco que siempre existe incertidumbre en este tipo de imputaciones y espero haber tomado la decisión más adecuada dentro del contexto del ejercicio.

# ***********************************************************************************************************************************

8. Identifique y elimine duplicados exactos y duplicados parciales definidos como registros
con el mismo id_paciente, fecha_prescripcion y medicamento. Reporte cuantos registros
se eliminaron en cada caso.

In [1048]:
# recupero el dataset desde el avance anterior
prescripciones = prescripciones_avance.copy()
# uso copy() para seguir trabajando desde el dataset que ya tiene fechas y dosis limpias
# esto evita perder el trabajo que ya hice en los puntos anteriores

In [1049]:
# reviso cuántos registros duplicados exactos hay en todo el dataframe
duplicados_exactos = prescripciones.duplicated().sum()
# uso duplicated() para identificar filas completamente repetidas
# una fila duplicada exacta significa que todos sus valores son iguales a otra fila
# uso sum() para contar cuántas filas duplicadas exactas existen
# guardo el resultado en duplicados_exactos para reportarlo después

duplicados_exactos
# muestro cuántos duplicados exactos encontré

np.int64(20)

In [1050]:
# identifico cuáles filas son duplicados exactos antes de eliminarlas
duplicados_exactos_filas = prescripciones[prescripciones.duplicated(keep=False)]
# uso duplicated(keep=False) para marcar todas las filas que están repetidas completamente
# no solo las segundas, sino todas las copias
# esto me permite ver exactamente qué registros se van a eliminar

duplicados_exactos_filas
# muestro los registros duplicados exactos

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
13,3006,2024-10-14,metformina,850.0,subcutanea,NaN,88.007742,23.0,SURA,MED-4054
32,8617,2023-12-05,ibuprofeno,400.0,oral,E11,50.170370,45.0,SANITAS,NaN
132,7723,2023-05-10,enalapril,250.0,oral,J06.9,67.122456,22.0,EPS Sura,MED-9359
155,2959,2024-09-03,ibuprofeno,100.0,oral,NaN,60.016445,78.0,Sura,NaN
179,4458,2025-07-05,ibuprofeno,400.0,oral,hipertension,78.487148,46.0,SURA,MED-4718
217,4629,2023-12-03,amoxicilina,500.0,subcutanea,Z00.0,64.267690,53.0,SANITAS,MED-0215
221,1653,2026-02-22,ibuprofeno,500.0,oral,K29.5,84.450763,NaN,SANITAS,MED-1189
249,4220,2024-11-01,enalapril,500.0,oral,I10,89.075624,41.0,SURA,MED-3263
293,4040,2026-01-22,amoxicilina,250.0,oral,I10,66.093916,69.0,COMPENSAR,MED-5989
302,2139,2024-12-16,ibuprofeno,250.0,oral,J06.9,70.391850,32.0,nueva eps,MED-9480


In [1051]:
# elimino los duplicados exactos del dataframe
prescripciones = prescripciones.drop_duplicates()
# uso drop_duplicates() para eliminar filas completamente repetidas
# esto conserva una sola copia del registro y elimina las repeticiones exactas
# aquí no estoy eliminando datos por valores faltantes, sino registros repetidos

# verifico nuevamente si quedaron duplicados exactos
prescripciones.duplicated().sum()
# uso duplicated().sum() otra vez para confirmar que ya no quedan duplicados exactos

np.int64(0)

In [1052]:
# reviso cuántos duplicados parciales hay usando id_paciente, fecha_prescripcion y medicamento
duplicados_parciales = prescripciones.duplicated(
    subset=['id_paciente', 'fecha_prescripcion', 'medicamento']
).sum()
# uso duplicated() con subset porque el profesor definió duplicado parcial con esas tres columnas
# subset me permite revisar duplicados solo en id_paciente, fecha_prescripcion y medicamento
# esto significa que si un paciente tiene el mismo medicamento en la misma fecha, se considera repetido
# uso sum() para contar cuántos registros cumplen esa condición
# guardo el resultado para reportarlo después

duplicados_parciales
# muestro cuántos duplicados parciales encontré

np.int64(0)

In [1053]:
# elimino duplicados parciales aunque no haya, para dejar el proceso completo
prescripciones = prescripciones.drop_duplicates(
    subset=['id_paciente', 'fecha_prescripcion', 'medicamento'],
    keep='first'
)
# uso drop_duplicates() como parte del flujo de limpieza
# aunque no haya duplicados, esto asegura consistencia en el proceso

# verifico que siga en 0
prescripciones.duplicated(
    subset=['id_paciente', 'fecha_prescripcion', 'medicamento']
).sum()
# esto confirma si la limpieza de duplicados parciales quedó bien

np.int64(0)

In [1054]:
# creo una tabla resumen con los duplicados eliminados
resumen_duplicados = pd.DataFrame({
    'tipo_duplicado': ['exactos', 'parciales'],
    'registros_eliminados': [duplicados_exactos, duplicados_parciales]
})
# uso pd.DataFrame para organizar el reporte en forma de tabla
# en tipo_duplicado indico si fueron exactos o parciales
# en registros_eliminados pongo cuántos se eliminaron en cada caso

resumen_duplicados
# muestro la tabla resumen para reportar el resultado

,tipo_duplicado,registros_eliminados
0,exactos,20
1,parciales,0


In [1055]:
# guardo el avance después de normalizar medicamento y via_administracion
prescripciones_avance = prescripciones.copy()
# uso copy() para guardar el dataset con fechas, dosis, medicamento y via_administracion ya limpios
# esto me permite seguir al siguiente punto sin perder lo que ya hice

#**Markdown**

profe, en este punto revisé la existencia de duplicados en el dataset diferenciando entre duplicados exactos y parciales según el criterio definido. primero identifiqué los duplicados exactos, es decir, registros completamente iguales en todas sus columnas, encontrando un total de 20, los cuales eliminé conservando una sola copia para evitar redundancia en la información. antes de eliminarlos, revisé cuáles eran esas filas para asegurarme de no perder información relevante, teniendo en cuenta que en datos de salud cada registro puede representar una atención real. por otro lado, al evaluar los duplicados parciales usando id_paciente, fecha_prescripcion y medicamento, no se encontraron casos, lo que indica que no hay prescripciones repetidas bajo ese criterio. aun así, apliqué el proceso de limpieza para mantener consistencia en el flujo. con esto logré depurar el dataset sin afectar la calidad ni el significado clínico de los datos.




# ***********************************************************************************************************************************

9. Unifique las variantes de eps en categorías canónicas. Puede usar un diccionario de
mapeo manual. Reporte la cardinalidad antes y después

In [1056]:
# recupero el dataset desde el avance anterior
prescripciones = prescripciones_avance.copy()
# uso copy() para seguir trabajando desde el dataset que ya tiene fechas y dosis limpias
# esto evita perder el trabajo que ya hice en los puntos anteriores

In [1057]:
# primero reviso los valores únicos de la columna eps porque antes de limpiar necesito entender cómo viene esta variable
# uso unique() porque me permite ver todos los valores diferentes sin repetirlos
# esto me ayuda a identificar si una misma eps está escrita de varias formas como mayúsculas, minúsculas o con espacios
prescripciones['eps'].unique()

array(['Compensar', 'NuevaEPS', 'Sanitas', 'COMPENSAR', 'Nueva EPS',
       'Sura', 'EPS Sanitas', 'SANITAS', 'SURA', 'nueva eps', 'EPS Sura'],
      dtype=object)

In [1058]:
# ahora calculo la cantidad de categorías diferentes antes de limpiar
# uso nunique() porque esta función cuenta cuántos valores únicos hay en la columna
# esto me sirve para tener una referencia inicial y luego comparar si la limpieza redujo la cantidad de categorías
cardinalidad_antes = prescripciones['eps'].nunique()

cardinalidad_antes
#aqui le pido que me muestre cuantos hay

11

In [1059]:
# guardo una copia de la columna eps original antes de cualquier limpieza
# uso copy() para no perder la información original mientras hago transformaciones
# esto me permite comparar después cómo venían los datos vs cómo quedaron
prescripciones['eps_original'] = prescripciones['eps'].copy()

In [1060]:
# hago una limpieza básica de texto antes de aplicar el diccionario
# uso str.strip() para eliminar espacios al inicio o al final de los textos porque esos espacios pueden hacer que una misma eps parezca diferente
# uso str.lower() para convertir todo a minúsculas y evitar que "COMPENSAR" y "compensar" se cuenten como categorías distintas
# esto me ayuda a reducir errores simples de formato antes de hacer un mapeo más específico
prescripciones['eps'] = prescripciones['eps'].str.strip().str.lower().str.title()


# vuelvo a revisar los valores únicos después de esta limpieza básica
# esto lo hago para ver si ya se redujeron algunas variaciones simples sin necesidad de usar el diccionario
prescripciones['eps'].unique()

array(['Compensar', 'Nuevaeps', 'Sanitas', 'Nueva Eps', 'Sura',
       'Eps Sanitas', 'Eps Sura'], dtype=object)

In [1061]:
# creo un diccionario de mapeo teniendo en cuenta que ahora todo está en formato tipo título (Title Case)
# esto es importante porque si no coincide exactamente, replace() no va a funcionar correctamente
# aquí defino cómo quiero que queden los nombres finales de cada eps
# esto es necesario porque en datos reales una misma entidad puede aparecer con nombres diferentes
mapa_eps = {
    'Compensar': 'Compensar',
    'Nuevaeps': 'Nueva Eps',
    'Nueva Eps': 'Nueva Eps',
    'Sanitas': 'Sanitas',
    'Eps Sanitas': 'Sanitas',
    'Sura': 'Sura',
    'Eps Sura': 'Sura'
}

# aplico el diccionario de mapeo a la columna eps
# uso replace() con un diccionario porque esta función permite reemplazar valores específicos por otros definidos por mí
# esto me permite agrupar diferentes formas de escribir una misma eps en una sola categoría
prescripciones['eps'] = prescripciones['eps'].replace(mapa_eps)


# reviso nuevamente los valores únicos después del mapeo
# esto me permite confirmar que las diferentes variantes ahora quedaron unificadas correctamente
prescripciones['eps'].unique()

array(['Compensar', 'Nueva Eps', 'Sanitas', 'Sura'], dtype=object)

In [1062]:
# calculo la cardinalidad después de la limpieza
# uso nuevamente nunique() para contar cuántas categorías quedaron después de aplicar el diccionario
# esto me sirve para comparar con el valor inicial y ver si efectivamente se redujo la cantidad de eps diferentes
cardinalidad_despues = prescripciones['eps'].nunique()

cardinalidad_despues
#aqui le pido que me muestre cuantos quedaron

4

In [1063]:
# finalmente comparo la cardinalidad antes y después
# esto me permite mostrar claramente el efecto de la limpieza sobre la variable eps
print("Cardinalidad antes:", cardinalidad_antes)
print("Cardinalidad después:", cardinalidad_despues)

Cardinalidad antes: 11
Cardinalidad después: 4


In [1064]:
# comparo cómo venían las eps originalmente vs cómo quedaron después de la limpieza
# uso drop_duplicates() para no repetir filas y ver solo las combinaciones únicas
# esto me permite visualizar claramente qué valores se transformaron
comparacion_eps = prescripciones[['eps_original', 'eps']].drop_duplicates()

comparacion_eps

,eps_original,eps
0,Compensar,Compensar
1,NuevaEPS,Nueva Eps
2,Sanitas,Sanitas
3,COMPENSAR,Compensar
4,Nueva EPS,Nueva Eps
5,Sura,Sura
7,EPS Sanitas,Sanitas
8,SANITAS,Sanitas
11,SURA,Sura
18,nueva eps,Nueva Eps


In [1065]:
prescripciones.head()
#solo lo hago para mirar como va quedando y que considero me hace falta

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id,eps_original
0,4355,2024-03-08,enalapril,250.0,oral,K29.5,79.586599,72.0,Compensar,MED-2771,Compensar
1,4442,2023-09-03,asa,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,Nueva Eps,MED-9403,NuevaEPS
2,8015,2026-04-10,enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN,Sanitas
3,4887,2026-01-19,metformina,500.0,subcutanea,hipertension,85.277837,NaN,Compensar,MED-4463,COMPENSAR
4,1406,2024-06-18,metformina,250.0,intravenosa,NaN,71.785582,47.0,Nueva Eps,MED-5819,Nueva EPS


In [1066]:
# elimino la columna eps_original porque ya cumplió su propósito de comparación
# uso drop() para eliminar columnas que no quiero en el dataset final
# especifico axis=1 porque estoy eliminando una columna y no filas
# esto me permite dejar el dataset limpio sin variables auxiliares que no se van a usar en el análisis final
prescripciones = prescripciones.drop(columns=['eps_original'])

In [1067]:
prescripciones.head()
#reviso que se hubiera eliminado esa ultima

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id
0,4355,2024-03-08,enalapril,250.0,oral,K29.5,79.586599,72.0,Compensar,MED-2771
1,4442,2023-09-03,asa,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,Nueva Eps,MED-9403
2,8015,2026-04-10,enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN
3,4887,2026-01-19,metformina,500.0,subcutanea,hipertension,85.277837,NaN,Compensar,MED-4463
4,1406,2024-06-18,metformina,250.0,intravenosa,NaN,71.785582,47.0,Nueva Eps,MED-5819


In [1068]:
# guardo el avance después de normalizar medicamento y via_administracion
prescripciones_avance = prescripciones.copy()
# uso copy() para guardar el dataset con fechas, dosis, medicamento y via_administracion ya limpios
# esto me permite seguir al siguiente punto sin perder lo que ya hice

#**Markdown**


Profe, en esta parte además de calcular la cardinalidad antes y después, quise ir un poco más allá y revisar exactamente cómo se transformaron los valores de la variable eps. Entonces lo que hice fue guardar una copia de la columna original y luego compararla con la columna ya limpia, para poder ver directamente qué cambios se estaban haciendo.

Al revisar esto me di cuenta que había muchos casos donde una misma EPS aparecía escrita de diferentes formas, por ejemplo “COMPENSAR”, “Compensar”, “NuevaEPS”, “nueva eps” o “EPS Sanitas”. En realidad todas estas representan la misma entidad, pero por diferencias en mayúsculas, espacios o cómo se escribió el nombre, el dataset las trataba como si fueran categorías distintas.

Por eso decidí hacer una limpieza primero de formato y luego aplicar un mapeo manual para unificarlas en categorías más claras como “Compensar”, “Nueva Eps”, “Sanitas” y “Sura”. Esto me permitió reducir la cardinalidad y dejar la variable mucho más consistente.

Esto es importante porque si no se hace esta unificación, en un análisis posterior se podrían obtener resultados incorrectos, ya que se estaría contando varias veces la misma EPS como si fueran diferentes.

# ***********************************************************************************************************************************

#**Nivel 3: Transformación y validación**

10. Cree la columna rango_etario con las categorías: 'pediátrico' (edad < 18), 'adulto' (18 a 64)
y 'adulto mayor' (>= 65). Asigne 'desconocido' a filas con edad invalida o NaN.

In [1069]:
# primero reviso la columna edad para entender qué valores tiene antes de crear la nueva variable
# uso describe() porque me permite ver estadísticas como mínimo, máximo y posibles valores raros
# esto me ayuda a identificar si hay edades negativas o NaN que debo tener en cuenta
prescripciones['edad'].describe()

,edad
count,482.000000
mean,51.053942
std,20.695726
min,-1.000000
25%,34.000000
50%,52.000000
75%,67.000000
max,200.000000


In [1073]:
# ahora creo las condiciones para clasificar la edad en rangos
# uso una lista porque voy a definir varias condiciones que luego voy a evaluar en orden
# cada condición representa un grupo de edad específico según lo que pide el ejercicio
condiciones = [
    (prescripciones['edad'] < 18),
    # aquí estoy diciendo que si la edad es menor a 18, entonces corresponde al grupo pediátrico
    # uso < 18 porque así estoy capturando niños y adolescentes

    (prescripciones['edad'] >= 18) & (prescripciones['edad'] <= 64),
    # aquí estoy definiendo el grupo adulto
    # uso >= 18 y <= 64 porque este rango incluye la mayoría de la población adulta
    # uso & porque necesito que se cumplan ambas condiciones al mismo tiempo

    (prescripciones['edad'] >= 65)
    # aquí defino el grupo adulto mayor
    # uso >= 65 porque a partir de esta edad se considera población de mayor riesgo en salud
]


# ahora defino las categorías que corresponden a cada condición
# uso una lista porque cada posición debe coincidir con las condiciones que definí arriba
# esto me permite asignar un nombre claro a cada grupo de edad
categorias = ['pediátrico', 'adulto', 'adulto mayor']


# ahora creo la nueva columna rango_etario usando las condiciones y las categorías
# uso np.select() porque esta función me permite evaluar múltiples condiciones y asignar valores según corresponda
# esto es mejor que usar varios if porque es más claro y funciona directamente con el DataFrame
prescripciones['rango_etario'] = np.select(condiciones, categorias, default='desconocido')

# uso default='desconocido' porque hay valores NaN o edades inválidas (como negativas)
# esto me permite no eliminar esos registros y marcar que no se puede clasificar ese paciente
# en datos de salud esto es importante porque un NaN no es solo un error, puede ser información faltante real

In [1074]:
# reviso los valores únicos de la nueva columna para verificar que se creó correctamente
# uso unique() para ver todas las categorías generadas
# esto me permite confirmar que las etiquetas quedaron como esperaba
prescripciones['rango_etario'].unique()

array(['adulto mayor', 'adulto', 'desconocido', 'pediátrico'],
      dtype=object)

In [1076]:
# convierto la columna rango_etario a formato tipo título (primera letra en mayúscula)
# uso astype(str) para asegurar que todos los valores sean tratados como texto
# uso str.title() para poner la primera letra en mayúscula y el resto en minúscula
# esto me ayuda a mejorar la presentación de la variable sin cambiar su significado
prescripciones['rango_etario'] = prescripciones['rango_etario'].astype(str).str.title()

# reviso nuevamente los valores únicos para confirmar el cambio de formato
# esto me permite verificar que ahora las categorías están bien presentadas
prescripciones['rango_etario'].unique()

array(['Adulto Mayor', 'Adulto', 'Desconocido', 'Pediátrico'],
      dtype=object)

In [1077]:
prescripciones.head()

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id,rango_etario
0,4355,2024-03-08,enalapril,250.0,oral,K29.5,79.586599,72.0,Compensar,MED-2771,Adulto Mayor
1,4442,2023-09-03,asa,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,Nueva Eps,MED-9403,Adulto
2,8015,2026-04-10,enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN,Adulto
3,4887,2026-01-19,metformina,500.0,subcutanea,hipertension,85.277837,NaN,Compensar,MED-4463,Desconocido
4,1406,2024-06-18,metformina,250.0,intravenosa,NaN,71.785582,47.0,Nueva Eps,MED-5819,Adulto


In [1080]:
# guardo el avance después de normalizar medicamento y via_administracion
prescripciones_avance = prescripciones.copy()
# uso copy() para guardar el dataset con fechas, dosis, medicamento y via_administracion ya limpios
# esto me permite seguir al siguiente punto sin perder lo que ya hice

#**Markdown**

Profe, en esta parte lo que hice fue crear una nueva columna que se llama rango_etario a partir de la edad del paciente, porque me di cuenta que es más fácil analizar por grupos que por edades individuales.

Entonces primero miré cómo venía la columna edad, porque en este dataset hay valores faltantes y también algunos valores que no tienen mucho sentido, como edades negativas. Teniendo eso en cuenta, definí tres grupos: pediátrico para menores de 18 años, adulto entre 18 y 64, y adulto mayor para 65 o más.

Luego lo que hice fue usar unas condiciones para clasificar cada paciente según su edad en uno de esos grupos. Y algo importante que tuve en cuenta fue que cuando la edad es NaN o inválida, no eliminé esos registros, sino que les asigné la categoría “Desconocido”, porque en datos de salud eliminar información puede hacer perder contexto del paciente.

También después ajusté el formato del texto para que las categorías quedaran más presentables, con la primera letra en mayúscula, como “Adulto”, “Pediátrico” y así.

Esto me ayuda porque ahora la variable queda mucho más organizada y lista para usar en análisis, por ejemplo para comparar comportamientos entre diferentes grupos de edad.

# ***********************************************************************************************************************************

11. Construya una tabla resumen agrupada por eps y via_administracion que incluya conteo
de prescripciones y estadísticas descriptivas de dosis_mg limpia.

In [1089]:
# recupero el dataset desde el avance anterior
prescripciones = prescripciones_avance.copy()
# uso copy() para seguir trabajando desde el dataset que ya tiene fechas y dosis limpias
# esto evita perder el trabajo que ya hice en los puntos anteriore

In [1090]:
# primero reviso que la columna dosis_mg ya esté limpia antes de hacer el resumen
# esto es importante porque las estadísticas dependen de que los datos estén correctos
prescripciones['dosis_mg'].describe()

,dosis_mg
count,496.000000
mean,427.620968
std,293.985476
min,100.000000
25%,200.000000
50%,400.000000
75%,500.000000
max,1000.000000


In [1091]:
# ahora agrupo los datos por eps y via_administracion
# uso groupby() porque me permite organizar la información por categorías
# en este caso quiero ver cómo se comportan las prescripciones según la eps y la vía de administración
tabla_resumen = prescripciones.groupby(['eps', 'via_administracion']).agg({
    'dosis_mg': ['count', 'mean', 'std', 'min', 'max']
})

# uso agg() para calcular varias estadísticas al mismo tiempo
# count me da el número de prescripciones
# mean me da el promedio de la dosis
# std me da la desviación estándar (qué tanto varían las dosis)
# min y max me muestran los valores extremos
# esto me permite tener una visión general del comportamiento de la dosis en cada grupo


# redondeo los valores para que la tabla sea más fácil de leer
# uso round() porque así evito muchos decimales innecesarios
tabla_resumen = tabla_resumen.round(2)


# muestro la tabla final
tabla_resumen

dosis_mg                               
                                count    mean     std    min     max
eps       via_administracion                                        
Compensar intravenosa              27  433.33  314.09  100.0  1000.0
          oral                     42  415.48  311.47  100.0  1000.0
          subcutanea               22  415.91  202.59  100.0  1000.0
Nueva Eps intravenosa              38  509.21  362.40  100.0  1000.0
          oral                     49  370.41  268.08  100.0  1000.0
          subcutanea               50  437.00  267.22  100.0  1000.0
Sanitas   intravenosa              50  408.00  278.00  100.0  1000.0
          oral                     58  446.55  323.07  100.0  1000.0
          subcutanea               43  391.86  279.65  100.0  1000.0
Sura      intravenosa              40  406.25  287.60  100.0  1000.0
          oral                     44  413.64  270.31  100.0  1000.0
          subcutanea               33  510.61  326.14  100.0  1000.0

In [1092]:
# reorganizo los nombres de las columnas para que sean más claros
tabla_resumen.columns = ['conteo', 'promedio', 'desviacion', 'minimo', 'maximo']

# esto me ayuda a que la tabla sea más legible y fácil de interpretar
tabla_resumen

conteo  promedio  desviacion  minimo  maximo
eps       via_administracion                                              
Compensar intravenosa             27    433.33      314.09   100.0  1000.0
          oral                    42    415.48      311.47   100.0  1000.0
          subcutanea              22    415.91      202.59   100.0  1000.0
Nueva Eps intravenosa             38    509.21      362.40   100.0  1000.0
          oral                    49    370.41      268.08   100.0  1000.0
          subcutanea              50    437.00      267.22   100.0  1000.0
Sanitas   intravenosa             50    408.00      278.00   100.0  1000.0
          oral                    58    446.55      323.07   100.0  1000.0
          subcutanea              43    391.86      279.65   100.0  1000.0
Sura      intravenosa             40    406.25      287.60   100.0  1000.0
          oral                    44    413.64      270.31   100.0  1000.0
          subcutanea              33    510.61      326.14   100.0  1000.0

In [1103]:
# ordeno la tabla por el conteo de prescripciones de mayor a menor
# uso sort_values() porque me permite identificar rápidamente los grupos más importantes
# esto me ayuda a interpretar mejor cuáles combinaciones de eps y vía tienen más volumen
tabla_resumen = tabla_resumen.sort_values(by='conteo', ascending=False)

tabla_resumen

,,conteo,promedio,desviacion,minimo,maximo
eps,via_administracion,,,,,
Sanitas,oral,58,446.55,323.07,100.0,1000.0
Nueva Eps,subcutanea,50,437.00,267.22,100.0,1000.0
Sanitas,intravenosa,50,408.00,278.00,100.0,1000.0
Nueva Eps,oral,49,370.41,268.08,100.0,1000.0
Sura,oral,44,413.64,270.31,100.0,1000.0
Sanitas,subcutanea,43,391.86,279.65,100.0,1000.0
Compensar,oral,42,415.48,311.47,100.0,1000.0
Sura,intravenosa,40,406.25,287.60,100.0,1000.0
Nueva Eps,intravenosa,38,509.21,362.40,100.0,1000.0


In [1104]:
# muestro los 3 grupos con más prescripciones
# uso head(3) para enfocarme en los casos más relevantes
# esto me permite identificar rápidamente patrones importantes en los datos
tabla_resumen.head(3)

,,conteo,promedio,desviacion,minimo,maximo
eps,via_administracion,,,,,
Sanitas,oral,58,446.55,323.07,100.0,1000.0
Nueva Eps,subcutanea,50,437.00,267.22,100.0,1000.0
Sanitas,intravenosa,50,408.00,278.00,100.0,1000.0


#**Markdown**

en esta parte construí una tabla resumen agrupando por eps y vía de administración para analizar cómo se comportan las prescripciones en cada grupo.

Lo que hice fue usar groupby para agrupar los datos y luego calcular varias métricas sobre la dosis_mg limpia, como el conteo de prescripciones, el promedio, la desviación estándar y los valores mínimo y máximo. Esto me permite ver no solo cuántas prescripciones hay, sino también cómo varían las dosis en cada caso.

Con esta tabla puedo comparar entre diferentes eps y también entre las vías de administración, por ejemplo ver en cuáles hay más variabilidad o en cuáles se manejan dosis más altas.

al ordenar la tabla resumen me di cuenta que hay combinaciones de eps y vía de administración que concentran una mayor cantidad de prescripciones. Esto puede indicar patrones en la forma en que se administran los medicamentos dependiendo de la entidad o del contexto clínico.

en esta parte ordené la tabla resumen de mayor a menor según el conteo de prescripciones, porque así es más fácil identificar cuáles son los grupos más importantes dentro del dataset.

Al hacer esto me di cuenta que algunas combinaciones de eps y vía de administración tienen mucha más cantidad de registros que otras. Por ejemplo, se observa que Sanitas con vía oral es el grupo con mayor número de prescripciones, seguido por Nueva Eps en subcutánea y nuevamente Sanitas en intravenosa.

Esto me permite ver que no todas las eps ni todas las vías se comportan igual, y que hay ciertos patrones en la forma en que se administran los medicamentos. También me ayuda a enfocar el análisis en los casos más relevantes en lugar de revisar toda la tabla sin un orden claro.

En general, este paso me sirvió para interpretar mejor los datos y no solo quedarme con el cálculo de las estadísticas.

# ***********************************************************************************************************************************

#**CONFIRMACION DEL DATASET ANTES DE DESCARGARLO**

In [1095]:
# reviso la estructura del dataframe
# uso info() para ver tipos de datos, valores no nulos y columnas existentes
# esto me permite confirmar que no hay columnas inesperadas como eps_original
prescripciones.info()

<class 'pandas.core.frame.DataFrame'>
Index: 496 entries, 0 to 499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   id_paciente         496 non-null    int64         
 1   fecha_prescripcion  496 non-null    datetime64[ns]
 2   medicamento         496 non-null    object        
 3   dosis_mg            496 non-null    float64       
 4   via_administracion  496 non-null    object        
 5   diagnostico_cie10   400 non-null    object        
 6   peso_paciente_kg    496 non-null    float64       
 7   edad                482 non-null    float64       
 8   eps                 496 non-null    object        
 9   prescriptor_id      450 non-null    object        
 10  rango_etario        496 non-null    object        
dtypes: datetime64[ns](1), float64(3), int64(1), object(6)
memory usage: 46.5+ KB


In [1096]:
# reviso los nombres de las columnas
# uso columns para confirmar que todas las variables están bien nombradas
# esto me ayuda a evitar errores al exportar o al analizar después
prescripciones.columns

Index(['id_paciente', 'fecha_prescripcion', 'medicamento', 'dosis_mg',
       'via_administracion', 'diagnostico_cie10', 'peso_paciente_kg', 'edad',
       'eps', 'prescriptor_id', 'rango_etario'],
      dtype='object')

In [1097]:
# verifico si aún existen duplicados en el dataset
# uso duplicated() para identificar registros repetidos
# esto me permite asegurar que la limpieza previa sí se aplicó correctamente
prescripciones.duplicated().sum()

np.int64(0)

In [1098]:
# reviso los valores faltantes finales
# uso isnull().sum() para contar NaN por columna
# esto me permite tener una visión final del estado del dataset
prescripciones.isnull().sum()

,0
id_paciente,0
fecha_prescripcion,0
medicamento,0
dosis_mg,0
via_administracion,0
diagnostico_cie10,96
peso_paciente_kg,0
edad,14
eps,0
prescriptor_id,46


Profe, en la variable edad encontré 14 valores faltantes. En este caso decidí no eliminar estos registros, ya que en un contexto de salud un valor faltante no es simplemente un error técnico, sino que puede representar que la información del paciente no fue registrada en el sistema.

Eliminar estos datos podría implicar perder información importante de otras variables como el medicamento, la dosis o la eps, que sí están disponibles. Por eso preferí mantener estos registros y reflejar esa ausencia de información mediante valores NaN y la categoría “Desconocido” en la variable rango_etario.

Esto permite conservar la mayor cantidad de información posible y al mismo tiempo reconocer que existen limitaciones en los datos.

 en las columnas diagnostico_cie10 y prescriptor_id me di cuenta que hay varios valores faltantes y también que no siguen un mismo formato. Por ejemplo, en diagnóstico hay mezcla de códigos como “K29.5” y también texto como “diabetes tipo 2”, y en prescriptor_id hay algunos valores vacíos.

En este caso decidí no modificar estas columnas, porque no es tan claro cómo limpiarlas sin dañar la información. Por ejemplo, no puedo simplemente cambiar o unificar los diagnósticos porque no todos están en el mismo formato, y en el caso del prescriptor, no tengo otra información que me permita completar los datos faltantes.

Por eso preferí dejarlas así y solo reconocer que tienen esos problemas. Considero que intentar cambiarlas sin un criterio claro podría generar errores en el dataset.

In [1094]:
# reviso las primeras filas para ver cómo quedó todo el dataframe
# uso head() porque me permite ver una muestra rápida del resultado final
# esto me ayuda a confirmar que las columnas nuevas como rango_etario sí están
prescripciones.head()

,id_paciente,fecha_prescripcion,medicamento,dosis_mg,via_administracion,diagnostico_cie10,peso_paciente_kg,edad,eps,prescriptor_id,rango_etario
0,4355,2024-03-08,enalapril,250.0,oral,K29.5,79.586599,72.0,Compensar,MED-2771,Adulto Mayor
1,4442,2023-09-03,asa,400.0,subcutanea,diabetes tipo 2,55.735352,48.0,Nueva Eps,MED-9403,Adulto
2,8015,2026-04-10,enalapril,200.0,intravenosa,NaN,72.782311,33.0,Sanitas,NaN,Adulto
3,4887,2026-01-19,metformina,500.0,subcutanea,hipertension,85.277837,NaN,Compensar,MED-4463,Desconocido
4,1406,2024-06-18,metformina,250.0,intravenosa,NaN,71.785582,47.0,Nueva Eps,MED-5819,Adulto


In [1100]:
# reorganizo las columnas pensando en una lectura más lógica del registro clínico
# primero dejo la identificación del paciente y la fecha, porque eso ubica el registro
# después dejo la información del paciente como edad, rango etario y peso
# luego dejo la información clínica como diagnóstico, medicamento, dosis y vía
# al final dejo la información administrativa como eps y prescriptor
# esto me ayuda a que el dataframe se lea de forma más ordenada y profesional

orden_columnas = [
    'id_paciente',
    'fecha_prescripcion',
    'edad',
    'rango_etario',
    'peso_paciente_kg',
    'diagnostico_cie10',
    'medicamento',
    'dosis_mg',
    'via_administracion',
    'eps',
    'prescriptor_id'
]

# aplico el nuevo orden de columnas al dataframe
# uso esta lista porque me permite decidir exactamente cómo quiero presentar la información final
# esto no cambia los datos, solo cambia el orden en que se muestran las columnas
prescripciones = prescripciones[orden_columnas]


# reviso las primeras filas para confirmar que el orden quedó como esperaba
# uso head() porque me permite validar visualmente que el dataframe quedó más claro
prescripciones.head()

,id_paciente,fecha_prescripcion,edad,rango_etario,peso_paciente_kg,diagnostico_cie10,medicamento,dosis_mg,via_administracion,eps,prescriptor_id
0,4355,2024-03-08,72.0,Adulto Mayor,79.586599,K29.5,enalapril,250.0,oral,Compensar,MED-2771
1,4442,2023-09-03,48.0,Adulto,55.735352,diabetes tipo 2,asa,400.0,subcutanea,Nueva Eps,MED-9403
2,8015,2026-04-10,33.0,Adulto,72.782311,NaN,enalapril,200.0,intravenosa,Sanitas,NaN
3,4887,2026-01-19,NaN,Desconocido,85.277837,hipertension,metformina,500.0,subcutanea,Compensar,MED-4463
4,1406,2024-06-18,47.0,Adulto,71.785582,NaN,metformina,250.0,intravenosa,Nueva Eps,MED-5819


In [1101]:
# reviso cuántas filas tiene el dataframe después de la limpieza
# uso shape porque me devuelve el número de filas y columnas
# el primer valor (posición 0) corresponde a la cantidad de filas
# esto me permite confirmar cuántos registros quedaron después del proceso
prescripciones.shape

(496, 11)

In [1102]:
# guardo el avance después de normalizar medicamento y via_administracion
prescripciones_avance = prescripciones.copy()
# uso copy() para guardar el dataset con fechas, dosis, medicamento y via_administracion ya limpios
# esto me permite seguir al siguiente punto sin perder lo que ya hice

# ***********************************************************************************************************************************

12. Exporte el DataFrame limpio como CSV con el nombre
prescripciones_limpias_[apellido].csv, sin columna de índice duplicada.

In [1107]:
# exporto el dataframe sin incluir el índice
# uso index=False para evitar que se guarde una columna adicional de índice
# esto me asegura que el archivo final no tenga columnas duplicadas o innecesarias
prescripciones.to_csv('prescripciones_limpias_[Rios].csv', index=False)

In [1108]:
# importo la librería files desde google.colab
# uso esta librería porque me permite interactuar con archivos dentro del entorno de Colab
# esto me sirve específicamente para poder descargar archivos que generé en el notebook

from google.colab import files


# descargo el archivo csv que acabo de crear
# uso files.download() porque esta función me permite bajar el archivo a mi computador directamente
# le paso como argumento el nombre del archivo que guardé anteriormente
# esto me ayuda a obtener el dataset limpio fuera de Colab para poder entregarlo o usarlo después

files.download('prescripciones_limpias_[Rios].csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>